### ISSUE TITLE
GLFW depends on a KDE project

### ISSUE THREAD

**Issue by onox** [glfw/glfw#1013]
[README.md](https://github.com/glfw/glfw#dependencies) says "GLFW itself depends only on the headers and libraries for your window system."

However, since c7f3bd0d22f11e68774de02f28472fd8d0eaebd9 GLFW requires [extra-cmake-modules](https://projects.kde.org/projects/kdesupport/extra-cmake-modules) if using Wayland for window creation. Is this (build) dependency on a KDE project desired?

**Comment by felipefs** [comment]
Was this just a copy-paste or a dependency addition? Mine compiles fine for Wayland, and I don't use KDE or extra-cmake-modules.

**Comment by onox** [comment]
> Was this just a copy-paste or a dependency addition?

(Build time) Dependency addition.

> Mine compiles fine for Wayland, and I don't use KDE and I don't have extra-cmake-modules installed.

How is that possible without ECM? The  commit says:

> We were using a copied FindWayland cmake script, but lets use the ones
from ECM (extra-cmake-modules) instead. This is more important in the
future when building extensions from wayland-protocols.

**Comment by felipefs** [comment]
>How is that possible without ECM?

Correction. I found that ECM isn't listed as installed in my repository, but somehow there's a old version of ECM in `/usr/share/ECM`.

I searched in the GLFW files, and the only usage of ECM that I found (https://github.com/glfw/glfw/blob/master/src/CMakeLists.txt#L42-L49) was two calls:
```
    ecm_add_wayland_client_protocol(glfw_SOURCES
        PROTOCOL
        ${WAYLAND_PROTOCOLS_PKGDATADIR}/unstable/relative-pointer/relative-pointer-unstable-v1.xml
        BASENAME relative-pointer-unstable-v1)
    ecm_add_wayland_client_protocol(glfw_SOURCES
        PROTOCOL
        ${WAYLAND_PROTOCOLS_PKGDATADIR}/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml
        BASENAME pointer-constraints-unstable-v1)
```

Maybe could be replaced, but I don't know how or if it's a big deal since the ECM can be installed without any other (KDE) dependency and is only part of the build step. In case anyone try to do that, I found the functions in the ECM repository: https://github.com/KDE/extra-cmake-modules/blob/a1d6d8f7259ade901a87b33edbef8b31bffb5e26/find-modules/FindWaylandScanner.cmake.

**Comment by elmindreda** [comment]
@onox What @felipefs said. While KDE did create extra-cmake-modules, it doesn't depend on any part of KDE and I believe it's become the canonical way to generate such protocol headers. KDE were pretty early adopters of CMake so it makes sense they'd be the ones to do this work.

It wasn't listed among the dependencies as the Wayland backend still isn't official, but it's pretty close now so you're right; it's time to add a note about it.

**Comment by onox** [comment]
> It wasn't listed among the dependencies as the Wayland backend still isn't official, but it's pretty close now so you're right; it's time to add a note about it.

Ok 👍
