### ISSUE TITLE
Mac Xbox Controller One/360 

### ISSUE THREAD

**Issue by Bilalmirza** [glfw/glfw#1033]
Glfw fails to recognise Button press/release for LT RT for Xbox Controller one/360
OS: macOS sierra

**Comment by Bilalmirza** [comment]
Tested this on windows... same result... cannot detect LT RT on xbox controller

**Comment by FlandreScarlet** [comment]
It's my guess that you are looking for the left and right triggers with `glfwGetJoystickButtons()` instead of `glfwGetJoystickAxes()`.

The axis states for joysticks is [documented here](http://www.glfw.org/docs/latest/input_guide.html#joystick_axis).

Does this help you, or did I misinterpret your problem?

**Comment by Bilalmirza** [comment]
Yes you are correct! thanks

Why isn't mapping provided by glfw. Each controller and OS has a different result.
PS L2 and R2 are not axes while xbox is.

**Comment by elmindreda** [comment]
@Bilalmirza Working on that right now. See #900 for progress updates.

**Comment by elmindreda** [comment]
@Bilalmirza FWIW, consistently mapped controller input is in `master` now via the new Gamepad functions.

**Comment by Bilalmirza** [comment]
Okay thanks :)
