### ISSUE TITLE
Choosing between normal fullscreen and windowed fullscreen mode

### ISSUE THREAD

**Issue by mikke89** [glfw/glfw#1036]
I'd like the user to be able to to select whether to use a normal fullscreen mode or a windowed fullscreen mode. By default, GLFW resorts to giving a windowed fullscreen mode if and only if the selected mode matches the current display mode. Is it possible to override this behavior in GLFW?

**Comment by FlandreScarlet** [comment]
As noted in [full screen windows documentation](http://www.glfw.org/docs/latest/window_guide.html#window_full_screen), you only get a full screen window if you specify a monitor for your window and as you said a windowed fullscreen mode is made by matching the selected mode with the current display mode.

You can choose a sensible default for your application, then offer the user the option of changing the behaviour, store their choice in some manner and on future execution of your application check whether the user has changed the options from the default behaviour before creating your window.

For switching between fullscreen mode and windowed fullscreen mode without recreating your window you would have to use the [glfwSetWindowMonitor()](http://www.glfw.org/docs/latest/group__window.html#ga81c76c418af80a1cce7055bccb0ae0a7) function.

Assuming I understood your question, the above should give you a decent idea of what to do and where to look for the related documentation. I hope it helps!

**Comment by mikke89** [comment]
Thanks for the quick response!
So I already let the user select between fullscreen and windowed fullscreen mode, as well is resolution (for normal fullscreen mode). The issue arises when the user selects a normal fullscreen mode at the desktop resolution, because GLFW by default wants to make this windowed fullscreen. 

As far as I know, the only way to get the proper behavior is to first select any other resolution when creating the window (fullscreen mode), and then use glfwSetWindowMonitor() to switch back to the desktop resolution. This doesn't seem like a very robust or elegant solution.

**Comment by FlandreScarlet** [comment]
After reading through the documentation and performing some tests myself I found out no way to force GLFW to create a fullscreen mode window at desktop resolution is that is not windowed fullscreen.

The next best thing I managed to do is setting the `GLFW_RESIZABLE` hint to `GLFW_FALSE`, then creating a window at a non-desired resolution that is a supported videomode and finally using `glfwSetWindowMonitor()` to change the window to the desired resolution. Which did require me to change the viewport with `glViewport()`. See relevant code sample below.

```
GLFWmonitor* primary = glfwGetPrimaryMonitor();
const GLFWvidmode* mode = glfwGetVideoMode(primary);
glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);

/* my native resolution is 1920x1080, 
** it would be better to grab a videomode rather than hardcoding a resolution like below, 
** but for testing purposes this works 
*/

GLFWwindow* window = glfwCreateWindow(1680, 1050, "example", primary, NULL);	
glfwSetWindowMonitor(window, primary, 0, 0, mode->width, mode->height, mode->refreshRate);
glfwMakeContextCurrent(window);

gladLoadGLLoader((GLADloadproc) glfwGetProcAddress);	
glViewport(0, 0, mode->width, mode->height);
glfwShowWindow(window);
```

You didn't mention whether you hide the window at first before creating the window and showing it after switching to desktop resolution or not. If you aren't, could you try it and see if that helps you? I hope this at least gives you the desired behaviour!

**Comment by mikke89** [comment]
Thanks for the example. Even though I hide the window initially, it does switch resolution to the temporary resolution. Which is not ideal as it messes with my other windows after I quit the application, and obviously is very flickery at startup so to say. But at least it seems like a work-around.

However, I do have some doubts whether I'm actually getting an exclusive fullscreen mode? At least alt-tabbing is as fast as in windowed fullscreen mode.

I also seem to have a separate issue (I think?) in that my refresh rate is always set to 60Hz whenever I change resolution through GLFW. My monitor supports up to 165 Hz. I have tried both setting the refresh rate to GLFW_DONT_CARE and 165 manually. I do get 165 Hz as a valid mode from GLFW, so it is detecting support for it.

**Comment by FlandreScarlet** [comment]
With a dual monitor setup I do not get the messing with windows or flickery at startup that you describe, do you happen to have some minimal code in which you still encounter this? What platform(s) do you encounter this on? I don't think I can help you that much more, but I would expect that the answers to these questions could make it easier for someone else to help you.

Alt-tabbing should still be very fast when you are at a native resolution, at least this is my experience with games in general, regardless of windowed fullscreen.

As for your refreshrate issue, I've read through some of the source code and in all *_window.c files except wl_window.c, the function `_glfwPlatformSetWindowMonitor` accepts a refreshrate parameter, but does not seem to be doing anything with it(on the master branch, latest commit). This may or may not be relevant to your issue.

@elmindreda should know about this and would likely want to know since it sounds like a bug, regardless of whether the above is relevant.

I would love to try and reproduce your refreshrate issue, but I lack a high refreshrate monitor for this.

**Comment by mikke89** [comment]
I used your exact code right now, by modifying simple.c, which resulted in the same problem. I'm on Windows 10 here. In fact, the GLFW_VISIBLE flag doesn't do anything for fullscreen it seems, only on normal windows. I never need to call glfwShowWindow() for it to show. 

As for the refresh rate issue. I poked around a bit for debugging purposes, and the correct refresh rate is initially being sent through the Windows API in ChangeDisplaySettingsExW(). In fact, I think I'm getting the correct video mode for exactly two frames (according to glfwGetVideoMode() being run in the game loop), before it switches to 60 Hz.
I also tried a few other commercial games and they all seem to work as expected, giving me 165 Hz at any resolution.

**Comment by elmindreda** [comment]
> By default, GLFW resorts to giving a windowed fullscreen mode if and only if the selected mode matches the current display mode. Is it possible to override this behavior in GLFW?

@mikke89 There is no difference between these things for OpenGL at the platform API level. The difference described in the documentation only refers to whether a video mode is set, but I phrased it in Direct3D terms as those are so pervasive in gamedev.

_Technically_ there are ways to explicitly choose between copying and page flipping on Windows. However, modern drivers appear to ignore these requests and instead decide whether a window gets page flipping based on its size, position and z-order. This as far as I can tell is the cause of #527.

> As far as I know, the only way to get the proper behavior is to first select any other resolution when creating the window (fullscreen mode), and then use glfwSetWindowMonitor() to switch back to the desktop resolution. This doesn't seem like a very robust or elegant solution.

@mikke89 That shouldn't affect the above behavior. Please don't do that.

> The next best thing I managed to do is setting the GLFW_RESIZABLE hint to GLFW_FALSE, then creating a window at a non-desired resolution that is a supported videomode and finally using glfwSetWindowMonitor() to change the window to the desired resolution.

@FlandreScarlet That shouldn't affect anything either. Did it have any effect? If so that may be a bug in GLFW.

> As for your refreshrate issue, I've read through some of the source code and in all *_window.c files except wl_window.c, the function _glfwPlatformSetWindowMonitor accepts a refreshrate parameter, but does not seem to be doing anything with it(on the master branch, latest commit).

@FlandreScarlet Yeah, that bit is a little hairy. The relevant line is [this one](https://github.com/glfw/glfw/blob/99762ad7f083c6fd8ae7e56c03043a0e3bec04ce/src/window.c#L851), where the desired video mode is updated in preparation for [this call](https://github.com/glfw/glfw/blob/99762ad7f083c6fd8ae7e56c03043a0e3bec04ce/src/win32_window.c#L1342) which in turn calls `_glfwSetVideoModeWin32`, but...

> As for the refresh rate issue. I poked around a bit for debugging purposes, and the correct refresh rate is initially being sent through the Windows API in ChangeDisplaySettingsExW(). In fact, I think I'm getting the correct video mode for exactly two frames (according to glfwGetVideoMode() being run in the game loop), before it switches to 60 Hz.
> I also tried a few other commercial games and they all seem to work as expected, giving me 165 Hz at any resolution.

@mikke89 ...this does sound like a bug in GLFW. Will look into it.

**Comment by FlandreScarlet** [comment]
>> The next best thing I managed to do is setting the `GLFW_RESIZABLE` hint to `GLFW_FALSE`, then creating a window at a non-desired resolution that is a supported videomode and finally using glfwSetWindowMonitor() to change the window to the desired resolution.

> @FlandreScarlet That shouldn't affect anything either. Did it have any effect? If so that may be a bug in GLFW.

@elmindreda this bit was a typo/mistake on my part, it should have said `GLFW_VISIBLE`. To my knowledge and from what I've seen `GLFW_RESIZABLE` does not affect fullscreen windows.

**Comment by mikke89** [comment]
@elmindreda Thanks for the clarification, I see there is no reason to distinguish between exclusive and windowed fullscreen mode then.
Please let me know if I can assist with the refresh rate issue.

**Comment by elmindreda** [comment]
@FlandreScarlet Ah, that makes sense. Thank you for the correction.

@mikke89 I can't seem to reproduce this with my Windows system and a monitor that supports the same resolution with different refresh rates. I always seem to get (and keep) the desired refresh rate. I'm not sure right now what information would be useful to get from your machine.

**Comment by mikke89** [comment]
Not sure what changed, but the refresh rate issue is no longer present on my end. Closing this as I cannot reproduce it anymore.
