### ISSUE TITLE
Auto-repeat of key presses not working under wayland

### ISSUE THREAD

**Issue by kovidgoyal** [glfw/glfw#1108]
Running the test/events program and holding down any key sends only a single press event, no repeat events.

Using the reference weston compositor and glfw compiled from master.

**Comment by kovidgoyal** [comment]
IIRC wayland has no key repeat, so it has to be implemented in the client. See WL_KEYBOARD_REPEAT_INFO_SINCE_VERSION

**Comment by linkmauve** [comment]
Hi, please test #1210, it should fix this issue. :)

**Comment by kovidgoyal** [comment]
Cool, thanks. I'll check it out when I have a moment.

**Comment by kovidgoyal** [comment]
I have not tried the code yet, but a couple of comments from quickly skimming the PR

1) Not all keys should be auto-repeated. For example, modifier keys are typically not auto-repeated. IIRC there is an API in libxkb to check if a key should be auto-repeated. 

2) timerfd is linux only. I dont know if it is available in BSD. A more portable (though harder to implement) design would be to adjust the timeout in the call to poll based on whether there is an active key press or not. That also avoids the need to sue an extra fd just for this.

**Comment by linkmauve** [comment]
Point 1 is now fixed in this PR.

I’m not sure how to fix point 2 yet, using a second fd instead of doing complex time computation was a no brainer for this feature, but I don’t have a good idea of what to fall back to in case it isn’t available, nor any way to test on another system with Wayland support but no timerfd. I’d prefer to merge this one first, so the majority will get this feature, and open another issue to check for Linux-specific things in this backend. Having CI run another OS would be extremely helpful for that btw, if you care about a specific one it would be a nice contribution.

**Comment by kovidgoyal** [comment]
Well If you want to use an fd instead of writing the timeout manipulation code, the way to use it is to use timer_create, which is POSIX compatible. The downside is that you then need to install an signal handler for some signal or create a thread. The former will break if the glfw using application also wants to set a signal handler for the chosen signal, the latter is fine, but a little more code to write and requires a second thread. See man timer_create and man sigevent

I dont personally care about any other platforms. I'm just pointing out the incompatibility, in case you were not aware of it. 

Anyway, I'll test the code and get back to you.

**Comment by kovidgoyal** [comment]
Actually, maybe you can get by with timer_create() without using a thread, since write() is signal safe, just have the function write to the wakeup fd.

**Comment by kovidgoyal** [comment]
I built kitty against this and key repeat works fine. So other than the cross-platform issue, looks good to me. Whether you care about the cross-platform issue or not is up to you. It should not be hard to implement changing the timeout. Something like (in pseudo-code):

```c
if (key_is_down) timeout = timeout < 0 ? now() - time_of_last_key_event : MIN(timeout, now() - time_of_last_key_event);
poll();
if (key_is_down && now() - time_of_last_key_event > repeat_interval) send_key_repeat();
```

And a little bit of code in the key event dispatch function to record the time of last key event.

**Comment by kovidgoyal** [comment]
Let me clean that up a bit:
```c
if (key_is_down) {
   time_to_next_repeat = repeat_interval - (now() - time_of_last_key_event);
   if (time_to_next_repeat <= 0) send_repeat();
   else { timeout = timeout = timeout < 0 ? time_to_next_repeat : MIN(timeout, time_to_next_repeat));
}
poll();
if (key_is_down && now() - time_of_last_key_event > repeat_interval) send_key_repeat();
```

**Comment by kovidgoyal** [comment]
I should note that the technique of modifying the timeout is also faster, since it avoids the extra syscall overhead from needing to read() the timer fd.

**Comment by kovidgoyal** [comment]
Oh and another issue just occurs to me, maybe I am mistaken, but wont this cause glfwWaitEvents(-1) to always return after the keyboard repeat interval? i.e. the timer fd will cause poll(-1) to never wait for more than ~500ms. That seems like a big CPU consumption regression.

**Comment by linkmauve** [comment]
It is already the case on other platforms, there is no way to opt-out from repeat events there. And whether we use a timerfd or a `poll()` timeout, we have the same amount of wakeups.

As for `read()` being one more syscall, I wouldn’t worry about that, we only do it once every ~100ms like you say so it’s entirely negligible.

I’ll play with this fallback method, but I fear it will complicate this function a lot.

**Comment by kovidgoyal** [comment]
No, I meant that the poll(-1) will return every 100ms even when no key is pressed. But, I was wrong about that, I missed the call to timerfd_settime() in keyboardHandleKey(). Which incidentally is another syscall (for key event) we can avoid by using timeout modification instead :)

A couple more issues I noticed:

1) You should set TFD_CLOEXEC on the fd, otherwise any application using glfw will pass the fd onto forked() processes even after an exec(). Also, probably a good idea to set TFD_NONBLOCK since you are reading after poll in any case. 

2) You read() only eight bytes in the call to read(). There could be more than eight bytes waiting. For example if the application using glfw does not call waitForEvents() for some time. You should either drain the fd fully, or at least make bug larger. 

Anyway, it's your code, your choice. I am just presenting alternatives.

**Comment by kovidgoyal** [comment]
Another (maybe?) issue. At least on X11 it is possible for the user to dynamically change the repeat rate using xset. I dont know if that is possible with wayland, if it is, then glfw will need to handle it.

**Comment by linkmauve** [comment]
I fixed your first point by adding `TFD_CLOEXEC`, but there is no reason to set `TFD_NONBLOCK` since we know we can read because `poll()` returned a `POLLIN` flag.

For your second point, there is no way for read to return more than eight bytes according to the manpage.  The number returned there is actually important in the exact case you described, where polling happens far apart, I fixed that too.

On Wayland the compositor can also totally change the repeat rate or initial timeout at any point, this implementation will keep the old rate until another key is pressed, I think that’s fairly non-problematic since most people will not change it at the same time as a key is pressed anyway.

I tried to implement a POSIX signal-based timer, but didn’t manage to do so without exploding the amount of code required and changing the signal behaviour of GLFW.  I also tried to use the `poll()` timeout instead, but there was a lot more calculation required than in your example code, and it was blowing up quite a lot in size too, I will merge this code as-is and open another issue to test the validity of the entire backend on all POSIX OSes.

**Comment by kovidgoyal** [comment]
Just FYI key repeat is currently broken in master. You are passing the wrong parameters to xkb_keymap_key_repeats. I have fixed that, and many other bugs witht he key repeat code in my fork, including getting rid of the unneccessary use of timerfd. https://github.com/kovidgoyal/glfw/commit/c848cf4bfaaa1c5882e99ecced598e4f3e892e22

Feel free to use my code, or not, as you wish. You might also be interested in: https://github.com/kovidgoyal/glfw/commit/b806f7fcf9c9641a2c6c1f73c12feb9a2085c6cf
