### ISSUE TITLE
Add glfwGetGamma function

### ISSUE THREAD

**Issue by ghuser404** [glfw/glfw#1124]
There is a `glfwSetGamma` function, which accepts `float`, but no mirrored `glfwGetGamma` function, which would return `float`.

Was it omitted as not being too useful?

**Comment by tombsar** [comment]
In general (I don't know of any exceptions) the gamma curve is stored by the host as a lookup table, rather than a single number. Whereas it is easy to generate a new gamma curve from an exponent (as is done in `glfwSetGamma`), there is no guarantee that an existing curve was generated that way. For example, sRGB is a combination of a linear ramp and a power law of 2.4, but the closest "pure" gamma curve is an exponent of 2.2.

The implementation of a hypothetical `glfwGetGamma` would need to do some kind of numerical least-squares fit to find an approximate result, but there would be no easy guarantees of robustness or correctness.

Have you found a need for this feature? I would be happy to draft such a function based around `glfwGetGammaRamp`, but IMO it belongs in client code rather than in glfw itself.

**Comment by ghuser404** [comment]
I'm not personally in need of such function, just thought it might be useful to someone.
However, I'm trying to learn gamma here, and I understand that simply using GLFW's gamma correction would not be enough, as that applies to the whole monitor, so I cannot gamma-correct a windowed window properly.

Do you have good learning sources?

**Comment by tombsar** [comment]
The Wikipedia articles on gamma correction and sRGB are a pretty good start for the theory:

https://en.wikipedia.org/wiki/Gamma_correction
https://en.wikipedia.org/wiki/SRGB

but it gets complicated in practice because of all the layers of software. Maybe someone else can chime in with advice, because I've always left the gamma curve alone (content in linear space, and ask OpenGL to do the linear->sRGB conversion for me).

**Comment by tombsar** [comment]
Untested, but the implementation might look something like this:

```
float getEffectiveGamma (GLFWmonitor * monitor) {
    GLFWgammaramp const * ramp = glfwGetGammaRamp(monitor);

    float sum = 0.0f;
    for (int i = 0; i < ramp->size; ++i) {
        float x = i / (float) (ramp->size - 1u);
        float y = ramp->green[i] / 65535.0f;
        sum += log2f(y) / log2f(x);
    }

    return sum / ramp->size;
}
```

**Comment by ghuser404** [comment]
Thanks for your effort. I think `glfwGetGamma` will not be useful in GLFW, so closing this ticket.

**Comment by Pyrdacor** [comment]
Sorry to revive this but I think this is somewhat useful. In OO languages there are properties to reflect the current state. Think of a VideoMode class with a gamma property. If we didn't set gamma at all, we need at least the information what the current gamma value is (e.g. default value for the monitor/OS). I don't know if glfw has better chances to retrieve such a value than the consuming library. In most cases a user of an application only wants to change a gamma value and not the entire ramp. But this also includes the information about the current value of gamma. When we change it, we can memorize it, but before that we don't know what value was set before. Here glfw could be of much help I hope.
