### ISSUE TITLE
What does the uninstall target do / how can we not create it

### ISSUE THREAD

**Issue by computersarecool** [glfw/glfw#1129]
Hi,

I asked the same question [on stack overflow](https://stackoverflow.com/questions/47259131/how-to-not-create-the-uninstall-target-when-using-glfw-and-cmake-on-windows) but apparently nobody there knows.

What does the `uninstall` target do that is generated in Visual Studio when using this with CMAKE?

How do we disable it?

It is not mentioned in the documentation, nor any of the code within the "install" target CMakelists itself.

If it must exist can it be automatically added inside the `GLFW3` folder instead of outside it?

**Comment by elmindreda** [comment]
> What does the `uninstall` target do that is generated in Visual Studio when using this with CMAKE?

It uninstalls the GLFW library, headers and package files from where the `install` target placed them (or will place them).

> How do we disable it?

It's disabled along with the `install` target. Use the `GLFW_INSTALL` CMake option to disable them.

> It is not mentioned in the documentation, nor any of the code within the "install" target CMakelists itself.

True, and it really should be included. There isn't really a section on installation at all and the rest of the compilation guide isn't all that great either.

> If it must exist can it be automatically added inside the `GLFW3` folder instead of outside it?

Absolutely! Fixed with aef4edadd0b580fd55a93299ac171caade586fe8.

**Comment by computersarecool** [comment]
Awesome answer. Great work.
