### ISSUE TITLE
Removing [NSApp run] doesn't change anything

### ISSUE THREAD

**Issue by medvednikov** [glfw/glfw#1165]
Hi,

This is more of a question rather than an issue.

I was learning how GLFW works on Mac and playing with it. I stumbled upon `[NSApp run]`. According to Apple docs, run() starts the event loop. That's exactly what it does when I create a simple Cocoa app from scratch.

However somehow in your code it doesn't block:

https://github.com/glfw/glfw/blob/master/src/cocoa_window.m#L1022

In fact it can be removed entirely and nothing changes! 

How does this work? Does glfw implement its own event loop? Then maybe [NSApp run] is not needed at all?

I see that in earlier versions there was no `[NSApp run]`, but `[NSApp finishLaunching]`.

**Comment by medvednikov** [comment]
I think I got it. You implement your own event loop in `_glfwPlatformWaitEvents`

Does it mean that it's safe to remove `[NSApp run]`?

**Comment by elmindreda** [comment]
This was introduced with 9aa15aa710ff5adbdbccb124da96864df84b2479 and is a hack to work around issues with the menu bar for un-bundled applications.

> However somehow in your code it doesn't block

It doesn't block because of the call to `stop` in `applicationDidFinishLaunching:`, which kills the loop as soon as it starts.

> Does it mean that it's safe to remove `[NSApp run]`?

It probably is as long as your application is bundled.

**Comment by medvednikov** [comment]
Got it, thanks for explaining. Cocoa is really confusing.
