### ISSUE TITLE
Function for showing a window without focusing it

### ISSUE THREAD

**Issue by ocornut** [glfw/glfw#1189]
> If it turns out you can't, we can add a function that only calls _glfwPlatformShowWindow.

This is a proposal for the function and issue discussed in 
https://github.com/glfw/glfw/issues/1179#issuecomment-359431211

Basically the current `glfwShowWindow()` effectively does both Show and Focus, which is ok for the majority of usage, but advanced use cases may not want to steal Focus. In fact, GLFW documentation itself advise against stealing focus if possible ;)

The new function would only do the Show part and I suggest the name **`glfwShowWindowWithoutFocus()`** but any name that you see fit would work.

**Comment by ghuser404** [comment]
I wonder, if `glfwShowWindow` is to be made to not steal focus in 4.0, will the `glfwShowWindowWithoutFocus` get removed then? It seems to really clutter the API.

**Comment by elmindreda** [comment]
Another possibility (not saying it's better): `glfwUnhideWindow`

@ghuser404 Yes on both counts.

**Comment by ocornut** [comment]
Yes I'm totally for removing in 4.0, it's a speciality function that will only affect a few.
 `glfwUnhideWindow()` seems less explicit, I can imagine people getting confused?

**Comment by ocornut** [comment]
Great idea! This solution looks ideal to me, much better than a new entry point :)

**Comment by elmindreda** [comment]
I would somewhat prefer a separate function, as it makes the call less ambiguous, but an hint would work too.

Is there need to track this option per window or would it work as an init hint?

**Comment by ocornut** [comment]
In my use case I need it selectively on a per-window basis (for the other features I already override window hints before creating a new window). I suppose if it was applied to all windows I could manually focus the window afterwards, though.

I like that the hints are not as visible/attractive to the end-user than an explicit function call, I think it is appropriate for such a specialized/advanced feature.

Anything that works is good for me of course!

**Comment by elmindreda** [comment]
All right, window hint it is then.

**Comment by dougbinks** [comment]
If you want me to do this, I'd be very happy to do so.

**Comment by elmindreda** [comment]
@dougbinks That would be great, thank you!

**Comment by dougbinks** [comment]
OK - I'll get on to this in a couple of days.

**Comment by dougbinks** [comment]
I have an initial implementation branched from master in [Add GLFW_FOCUS_ON_SHOW](https://github.com/dougbinks/glfw/commit/9d1224a9322fe2a1f97c84b91ea5cfb8488d8ebd).

This is a relatively trivial addition, introducing a new define for a window hint and attribute, with all behaviour implemented in the platform independent layer, plus a minor alteration of the test windows.c to change the focus behaviour of all but the first window on being shown.

I've added some documentation in the header but if this seems like the right direction I can take a look at extending the full documentation.

Main questions / issues:

1. Name - I chose GLFW_FOCUS_ON_SHOW to reflect glfwShowWindow() naming, and as GLFW_FOCUSED_ON_SHOW reads more like a prior state than a setting.
1. Define value & position in header - I chose 0x0002000C for compatibility, and placed it at the end of window hints/attribs rather than next to GLFW_FOCUSED.
1. Attribute - as this could be set per window I've made it an attribute so it can be read back by the user. This could be removed as the user can maintain this, but as it's required in the window struct this offers little advantage.

Any thoughts welcome, though if I don't hear anything in a few days I'll add documentation and submit a pull request.

**Comment by dougbinks** [comment]
After some thought it also makes sense to add GLFW_FOCUS_ON_SHOW as a supported attributed for glfwSetWindowAttrib:

https://github.com/dougbinks/glfw/commit/1f69a5dcc075015692d9f26db359f9b6a3f8e0d6

The prior commit to this fixes a few TAB errors, apologies and thanks to @ocornut for spotting.

**Comment by ocornut** [comment]
Thank you @dougbinks , @elmindreda !
