### ISSUE TITLE
Adopt "Flicks" as unit of time

### ISSUE THREAD

**Issue by tombsar** [glfw/glfw#1190]
(Tentative feature request for a future API update; opinions wanted)

OculusVR (Facebook) recently announced a new unit of time, intended to be used for multimedia applications. To quote their README (https://github.com/OculusVR/Flicks):

> This unit of time is the smallest time unit which is LARGER than a nanosecond, and can in integer quantities exactly represent a single frame duration for 24hz, 25hz, 30hz, 48hz, 50hz, 60hz, 90hz, 100hz, 120hz, and also 1/1000 divisions of each.

This sounds interesting to me. There are a few of us that want to move away from using floating-point numbers to represent time in the glfw API, and this would, at the very least, give a not-completely-arbitrary basis for that. It remains to be seen if this will gain any traction outside of OculusVR.

**Comment by ghuser404** [comment]
While I'm all up for a good time API, the flicks seem to be tightly related to specific use cases, such as refresh rates, etc. Moreover, in their README they mention that it actually works great with C++'s `std::chrono::high_resolution_clock`:
> This makes it suitable for use via std::chrono::duration and std::ratio for doing timing work against the system high resolution clock, which is in nanoseconds, but doesn't get slightly out of sync when doing common frame rates.

So if we want to change time API to 'something-better', keeping in mind the above, the question is:
What is wrong with nanoseconds for a generic API, like GLFW?

**Comment by elmindreda** [comment]
It's definitely something to keep an eye on.

**Comment by blackencino** [comment]
Hi! I'm the author of the "Flicks" repo.

The genesis of that project was exactly motivated by nanoseconds being ill-suited. Here's a practical example. Let's say that you are working in film, at 24 frames per second, and you want to express a frame duration in your time units (nanoseconds in this example). So you do something like this (assuming being inside std::chrono, in C++)

```
// Compute the duration of a 24 fps film frame in nanoseconds
constexpr nanoseconds frame_increment = duration_cast<nanoseconds>(duration<int, ratio<1, 24>>{1});

// Now compute the duration of 24 of these
constexpr nanoseconds one_second_of_frames = 24 * frame_increment;

// Compute the number of nanoseconds for one second.
constexpr nanoseconds one_second = duration_cast<nanoseconds>(seconds{1});

// What happens now?
static_assert(one_second_of_frames.count() == one_second.count(), "Synchronization error");
```
Here's an ideone link which shows what happens when you attempt to compile the above: (spoiler, it fails!)

https://ideone.com/fJTgl1

The whole idea behind flicks was to create a time unit which was as close to nanoseconds as possible, for maximum precision, while being able to *exactly* represent frame (and sample) increments for most media types, as well as power-of-ten subdivisions of same. Since we created this, we've been using it instead of nanoseconds, and it works a charm. It's convenient, and then when you want to do things like have specific events trigger when the incremented time is *exactly* three seconds (or something like that), you don't have to write finicky code. Plus, during the genesis of this work, the unit was vetted by a pretty wide group with expertise in a few industries, including visual effects, games, and professional audio.

Here's the same example as above, written with flicks.

https://ideone.com/5HeK4z

This one works!

Please note that we fully acknowledge that this unit of time is a convenience, certainly not a necessity. But it is a nice convenience! Anyway, I hope you choose flicks, but if you don't, I can understand. 

Chris Horvath

**Comment by blackencino** [comment]
Also, I should add... when I first took a stab at this, I considered using Maya's "tick", which is 1/600 of a frame, but it isn't high precision enough for things like high-speed simulations where sometimes we're computing in 1/1000 of a frame increments.  I also looked at using some variation of jiffy, which are defined here: https://en.wikipedia.org/wiki/Jiffy_(time), but again they didn't quite fit.

**Comment by meshula** [comment]
For media related apps such as DAWs and animation programs, it definitely makes sense to use a timebase that allows exact representation of framerate, otherwise errors tend to compound as a user makes edits so I'll be using Flicks for that sort of thing. I think the fundamental question is what is the relation of glfw to time keeping? On a system with std::chrono available, one might use it directly instead of glfw's timers.

**Comment by ghuser404** [comment]
@blackencino Flicks are definitely a good thing! I just wonder how it fits into GLFW.

1. For games you would want to allow user to cap their framerate to any value between 30-300 fps. With flicks you cannot represent them all.
2. OSs don't count time in flicks, they do so in ms, ns, etc. So if GLFW was to return flicks instead of time units that OS returns, you would be losing precision. This is crucial for someone who actually wants to receive, say, nanoseconds.

How I see one could use flicks with GLFW, is use them in their code to count frames, while GLFW keeps returning time that OS returns. If you have to deal with precise framerates from a limited set (24, 30, 60, etc.), and not a range of 30-300, then flicks are a very helpful thing.
