### ISSUE TITLE
Why filter unicode points?

### ISSUE THREAD

**Issue by OlivierSohn** [glfw/glfw#1215]
https://github.com/glfw/glfw/blob/58cc4b2c5c2c9a245e09451437dd6f5af4d60c84/src/cocoa_window.m#L802

On OSX, some unicode characters are filtered. As there is no comment surrounding this code, I wonder why that is, and checked in the unicode ranges : https://en.wikipedia.org/wiki/Unicode_block, and found that this will filter for example https://en.wikipedia.org/wiki/Alchemical_Symbols_(Unicode_block) and https://en.wikipedia.org/wiki/Geometric_Shapes_Extended.

I don't understand, and think it is a mistake, and that the filtering should be removed. What do you think?

**Comment by GreenLightning** [comment]
The code points you mentioned are all in the Supplementary Multilingual Plane (SMP), i. e. they are of the form 1XXXX, but maybe the check was only meant to filter characters from the Basic Multilingual Plane (BMP), which are of the form 0XXXX or just XXXX for short.

The code points F7XX fall into the range U+E000..U+F8FF which is declared as a Private Use Area and after some digging I indeed found this document in which Apple maps some of the filtered code points "for transient use as keyboard function keys":

[ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/CORPCHAR.TXT](ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/CORPCHAR.TXT)

So the check might or might not target only these code points and it might or might not do so because Apple uses them for function key related stuff and potentially sends them to your application to which they probably appear as garbage.

**Comment by OlivierSohn** [comment]
Thanks, it makes sense! Also, I found that unichar is a 2 byte type so it cannot represent the unicode points I mentionned. I guess the code is ok then, maybe just adding the comment with your explanation would be the fix.

**Comment by GreenLightning** [comment]
Uhhhh, right, I didn't look at the surrounding code. Considering that unichar is a 2 byte type which actually represents UTF-16 code units, the check only filters out the unicode code points U+F700 to U+F7FF, as code points from other planes are encoded as surrogate pairs.

**Comment by OlivierSohn** [comment]
So I understand we agree the code is ok. I was going to do a pull request to add a comment, but then thought that it would probably be best to handle this more generally, in _glfwInputChar, to filter out "Private Use Area" unicodes for all platforms.

It will help users write code that is more platform-independenant...

But I guess at this point we need to know what the library maintainers think of this (@elmindreda ?).

**Comment by elmindreda** [comment]
To my knowledge macOS is the only platform that does this so I prefer keeping in as a platform-specific detail.
