### ISSUE TITLE
Raw mouse input

### ISSUE THREAD

**Issue by Opioid** [glfw/glfw#125]
It would be cool if GLFW had access to raw mouse intput data without pointer acceleration etc.
On linux this is apparently possible with xinput2.
Any plans for this?

**Comment by httpdigest** [comment]
I would provide high-precision mouse input for Windows via WM_INPUT messages, as I am needing high-precision mouse movement without pixel-raster and ballistics right now.
Would provide it as a patch for GLFW once it's done.
I am following the instructions on:
  http://msdn.microsoft.com/en-us/library/windows/desktop/ee418864(v=vs.85).aspx
for that.

**Comment by httpdigest** [comment]
@elmindreda Regarding the support for high-precision raw mouse input, would you consider it a good idea to have a window creation flag (for glfwWindowHint) such as GLFW_MOUSE_USE_RAW_INPUT with 0 (disabled, would use WM_MOUSEMOVE) and 1 (enabled, would use WM_INPUT with raw values)?
I currently don't know what your plans are for the support of other OS'es.

**Comment by elmindreda** [comment]
My plan is to have high precision input always be enabled where possible, i.e. where it's separate from raw input. This is already done on X11. Raw input, in the sense of un-accelerated, I'm intending to enable only for disabled cursor mode. I believe it's rarely useful data when the system cursor is visible.

**Comment by shurcooL** [comment]
> Raw input, in the sense of un-accelerated, I'm intending to enable only for disabled cursor mode. I believe it's rarely useful data when the system cursor is visible.

I agree that un-accelerated positional data is rarely useful when the system cursor is visible, but un-accelerated _delta_ data might be useful.

In those situations, you would typically want to temporarily hide the system cursor too, but that's not always the case.

**Comment by httpdigest** [comment]
Thanks for the info! I now have a Windows-working version. The code on the MSDN-article is actually partly wrong and doesn't work. :-)
You are right. It is only useful when the cursor is disabled, since also on Windows it only gives relative mouse movement which is not pixel-raster-related.
What exactly do you mean with "high precision input always be enabled where possible?"
As I see it, on Windows you can only have pixel-raster-related WM_MOUSEMOVE (which is not high-precision) or use relative raw input values which are high-precision (because not pixel-raster-related).

**Comment by httpdigest** [comment]
> @shurcooL: I agree that un-accelerated positional data is rarely useful when the system cursor is visible, but un-accelerated delta data might be useful.

I totally agree! I am thinking of any application/game (like a first-person) where you want very little movement to still be recognized by your input system, which the standard pixel-raster mouse input would not.

**Comment by httpdigest** [comment]
Okay,
after having investigated GLFW's code more, in my opinion the best option would be to have an additional callback function:

  void(\*GLFWrawmousemotionfun)(GLFWwindow\* win, int dx, int dy)

That way we can have both:
- raw relative high-precision mouse motion (via WM_INPUT)
- and pixel-raster cursor positions (via WM_MOUSEMOVE).

Windows reports both. Don't know about the other OS'es though.

And that solution would also not overload the meaning of the existing cursorpos callback, which is always related to pixel-raster cursor position.

What do you think about that?
Thanks!

**Comment by httpdigest** [comment]
I made a working draw version of the proposed changes under a fork of GLFW.
These are the changes: https://github.com/httpdigest/glfw/commit/33b56073740277d18fcf0d880852373df164e606

**Comment by shurcooL** [comment]
I agree.

Many user applications are interested in delta mouse movements. They often have to calculate it from cursor positions, which is complicated, error prone, and often gives you delta input which is polluted by cursor acceleration.

I've suggested this in the past (see https://github.com/glfw/glfw/issues/193#issuecomment-30598375) and I still think it's a good idea:

> I really think a proper solution (that requires improving/breaking the API) is to expose the mouse input as two independent types of events. Relative mouse movement deltas (always sent, preferably ignoring mouse acceleration), and absolute cursor position updates (only issued when cursor is visible, naturally includes OS-level mouse acceleration).

> Hiding, showing, and moving the cursor via glfwSetCursorPos() should cause zero mouse movement deltas.

> It's unfortunate that every user of GLFW that cares about both relative and absolute mouse positions has to do the non-trivial (and error prone) calculation on their own, despite the physical input device generating true relative deltas. All because improving it requires an API change.

**Comment by httpdigest** [comment]
Yeah well,
I just provided a working Windows-version for it, that you are very welcome to use and test for bugs/issues (if you use Windows, that is :), especially related to your mentioned "setting the cursor position should not issue a delta movement."
That would help in improving the draft version for a final inclusion into GLFW:master. If @elmindreda is okay with that, of course.
And also GLFW would also need support for other OS'es then.
Another great thing I just noticed: Even if your cursor is at the edge of your screen, you still get relative mouse movements beyond that. So, no need to artificially reposition your cursor to the screen center everytime. Just hide it. :-)

**Comment by shurcooL** [comment]
> Even if your cursor is at the edge of your screen, you still get relative mouse movements beyond that.

Yep. That's another advantage of this approach. If you're specifically asking for mouse movement delta offsets, and the physical mouse keeps moving, you should keep receiving accurate delta offsets regardless if cursor position happens to be at the edge of screen or not.

I use OS X and I could contribute a PR that tries to implements it (and report any issues/difficulties I run into), if desired. But first we need agreement about the API (addition, it would seem, as to not break backwards compatibility?). And I imagine this would be slated for 3.2.

**Comment by httpdigest** [comment]
> I could contribute a PR that tries to implement it (and report any issues/difficulties I run into), if desired

It is highly desired, as you just said before. Many applications desire such a delta movement information. So, I'd say: Think about a way of doing it (like using an additional callback function, like I did) and then just do it! :-)
Provide a working draft version that can be discussed about then.

Less talk, more action! :-)

**Comment by shurcooL** [comment]
Sounds good. Unless @elmindreda tells me not to, I'll create a working draft implementation for OS X.

**Comment by httpdigest** [comment]
:-) she is responsible for GLFW and it's overall architecture and her task is to coordinate the working on her project and of course ultimately to decide what goes in and what stays out.
But in my opinion, such open-source projects live and thrive from community effort that is openly encouraged. So of course she cannot forbid you or tell you not to do it.
She can refuse to have it incorporated into GLFW finally, but after all, you have then created something that for you and possibly others that works and that you can share.
So, that was a little talk from me, don't mind that. :-)

**Comment by httpdigest** [comment]
Hey @shurcooL , just had a view on a possible Mac OS X implementation.
You probably know this, but I think you have to use IOKit/hid/IOHIDLib.h with IOHIDValueGetScaledValue.
Here is an example [http://ysflight.in.coocan.jp/programming/macosx/samples/JoystickSample.cpp] even though it says "joystick"-sample it also applies to mice, it seems.

**Comment by shurcooL** [comment]
I've started investigating a possible API for this; see 2 commits above.

So far, it looks really good.

On the browser side, I had no choice but to add it in order to support getting mouse movement deltas while cursor is disabled in the browser, because:

> #### Locked state
>
> When Pointer lock is enabled, the standard MouseEvent properties clientX, clientY, screenX, and screenY are held constant, as if the mouse is not moving. The movementX and movementY properties continue to provide the mouse's change in position. There is no limit to movementX and movementY values if the mouse is continuously moving in a single direction. The concept of the mouse cursor does not exist and the cursor cannot move off the window or be clamped by a screen edge.

(See https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API for reference.)

So the normal cursor position callback was not working when the cursor is disabled via Mouse Lock API.

It is my current opinion that that is a very wise and good design decision to treat the cursor (and its position) as non-existent when it is disabled. So far I am a big fan of the web APIs provided for mouse input, and I think GLFW can be improved by adding `MouseMovementCallback`. For that reason, I will proceed to try to make a PR that implements it for OS X.

**Comment by shurcooL** [comment]
Ok, I've gone with the following signature for the mouse movement callback in my testing so far:

```
func MouseMovementCallback(w *Window, xdelta float64, ydelta float64)
```

It worked great in an app where I needed delta mouse movement input exclusively.

Now that I have an app where I want (at different times) both absolute cursor position updates, as well as  relative movement deltas, it feels odd having two separate callbacks. Joining the two generated events into one is tricky. So now I'm considering the following "superset" callback signature:

```
func MouseEventCallback(w *Window, xpos float64, ypos float64, xdelta float64, ydelta float64)
```

Still thinking this through (and I might find a way to make the 2 separate callbacks work well), but I just wanted to post my current findings here.

**Comment by shurcooL** [comment]
An update here. I've decided to go through with that idea to have a more complete callback that provides information about latest known cursor position, as well as the raw mouse movement delta.

See the change in https://github.com/shurcooL/goglfw/commit/bbb7dd08d2a54291123d9cca50282fed9954ce65.

The motivation is that both types of events originate from the **exact same underlying physical event**, the user moving the physical mouse on a surface. Therefore both events often happen together as one unit, at the exact same point in time.

Note that sometimes only one of two events will be present. Namely, if there's no mouse cursor position update, then the same cursor position as before will be provided. If there's no raw delta motion event (i.e. consider the case where mouse cursor is repositioned via programmatic means, without the user physically moving the mouse; that results in new cursor position, but zero delta motion), then the delta is 0.

I'm using the new callback API in my testing in order to evaluate how it works out, and so far it seems good. Both from implementing it inside glfw, as well as using it outside of glfw perspectives.

**Comment by shurcooL** [comment]
After spending more time with that change, I am very content with it and feel no need to change it any further, at least at this time.
