### ISSUE TITLE
why there is no glfw3.c (some questions about source code)

### ISSUE THREAD

**Issue by 243750496** [glfw/glfw#1256]
if you packed up api
you should pre-comple glfw3.c and glfw3.h together and get lib and dll files to use the api 

Q1:but why there is no glfw3.c ?? if no glfw3.c how you creat lib and dll ? 
Q2:there is something like GLFW_PLATFORM_ERROR defined in glfw3.h , you do not include glfw3.h , but why it finally compiled and created dll and lib successfully

**Comment by tombsar** [comment]
I'm guessing you're fairly new to programming? Non-trivial projects often split their source code up across multiple files, and use a build system to tell the compiler which files to compile, and how to link everything together into an executable or library. You can name the source files and outputs however you like, which is why the project doesn't need a `glfw3.c`. You can find the glfw build list here: https://github.com/glfw/glfw/blob/master/CMakeLists.txt but it's rather difficult to understand if you are not used to working with CMake. There are instructions on how to compile glfw here: http://www.glfw.org/docs/latest/compile_guide.html

`glfw3.h` *is* included by the source code, via `internal.h`. If it wasn't included, there would be compile errors due to the undefined symbols.

This isn't really an issue, so I suggest you post over in the forum for this kind of discussion in future: http://discourse.glfw.org/

**Comment by 243750496** [comment]
thanks  for help!
