### ISSUE TITLE
Wayland window decorations not shown

### ISSUE THREAD

**Issue by christianrauch** [glfw/glfw#1257]
I built glfw with `GLFW_USE_WAYLAND=1` from current master (commit 23dfeee4cb4fac69f0b1f3614c4305e2129cf43b) and have problems with the client side window decorations.

The window decorations are shown when launching `examples/simple` in the terminal in Weston 3.0.0 (Ubuntu 18.04 in VirtualBox 5.2.10). I can move and resize the window.

They are **not shown** on GNOME shell 3.28.1 and kwin 5.12.4 (Ubuntu 18.04 in VirtualBox 5.2.10). The window decorations are also not shown under Weston 1.9.0 (on Ubuntu 16.04)

**Comment by christianrauch** [comment]
The missing window decoration is caused by the renaming of Wayland interfaces. The decorations are using `wp_viewporter` which was previously named `wl_scaler`. However, neither of these interfaces are available on Gnome 3.28 and I believe that the new `xdg_wm_base` is supposed to include this functionality.
Is there a chance that the resizing functionality will make use of the `xdg_wm_base`?

**Comment by linkmauve** [comment]
GNOME should get it once they resolve this issue: https://gitlab.gnome.org/GNOME/mutter/issues/132
For Kwin I haven’t been able to find a bug report, you may want to report one yourself.
As for Weston, I don’t plan on supporting old versions as it isn’t a desktop environment and thus not something most users will end up using as their daily driver, and because this `wl_scaler` protocol would have to be embedded in GLFW’s sources rather than pulled from wayland-protocols.

For Kwin and possibly other compositors, a totally different approach could be used, where GLFW would instead ask the compositor to decorate our window itself, I’m only waiting for the protocol to end up in wayland-protocols, see: https://github.com/glfw/glfw/pull/1161#issuecomment-361238461

**Comment by gracicot** [comment]
With Wayland Protocols 1.15, a new XDG-Decoration has been added, which means there is now a common way to ask for decorators to draw decorations. https://lists.freedesktop.org/archives/wayland-devel/2018-July/038831.html

**Comment by christianrauch** [comment]
But it is not guaranteed that desktop shells will implement this. Maybe there should be an alternative way to draw client-side decorations.

**Comment by linkmauve** [comment]
gracicot, thanks for the notification, I’ll look for a compositor to develop this against.

christianrauch, there already is one, as long as `wp_viewporter` is supported.

**Comment by christianrauch** [comment]
I know that the viewporter is an official and stable protocol extension. But the real problem I wanted to make aware of in this issue is that it is not (yet) supported in major desktop environments like Gnome and KDE.
It might be better to manually implement this functionality, using the core protocol only, to support more desktop environments.

**Comment by linkmauve** [comment]
[xdg-decoration](https://cgit.freedesktop.org/wayland/wayland-protocols/tree/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml) is now implemented in GLFW (as of #1341), adding support for server-side decorations in compositors implementing this protocol.

Neither GNOME nor KDE support it yet, so I’m reoppening this bug.

**Comment by linkmauve** [comment]
KDE, as of KWin 5.15, [now supports `xdg_decoration`](https://phabricator.kde.org/D17756), and GNOME [now supports `wp_viewporter`](https://gitlab.gnome.org/GNOME/mutter/merge_requests/323), for the upcoming 3.32 release.

We can now close this issue as all relevant compositors now support one of these two protocols, if any user still doesn’t see decorations we can just tell them to update their compositor. 🙂
