### ISSUE TITLE
CMAKE unable to find Vulkan (using Visual Studio 15 2017 Win64)

### ISSUE THREAD

**Issue by Jelly-Fish-Dev** [glfw/glfw#1301]
Trying to build it with CMAKE returns 
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)

**Comment by elmindreda** [comment]
Do you have the [LunarG Vulkan SDK](https://vulkan.lunarg.com/) installed?

Note that GLFW is built with Vulkan support even when the SDK isn't found. The SDK is only used to build a test program.

**Comment by vilya** [comment]
I believe this is already fixed in the 3.3 development branch(?), but just for reference: this happens because newer versions of CMake ship with their own FindVullkan module which overrides the copy in GLFW and defines output variables with different capitalisation to what the rest of the GLFW build expects (i.e. Vulkan_LIBRARY rather than VULKAN_LIBRARY).

**Comment by elmindreda** [comment]
Thanks to glad, the GLFW CMake files no longer look for Vulkan. Closing this as stale.
