### ISSUE TITLE
High CPU load of glfwPollEvents() in Vulkan app

### ISSUE THREAD

**Issue by hsa-online** [glfw/glfw#1303]
Developing Vulkan app with GLFW I noticed that when an OpenGL context is not created on window creation and `glClear(...); glfwSwapBuffers(...);` weren't called in the main loop, the app completely consumes one of my CPU cores.

Profiler says that the "Total CPU (%)" for `glfwPollEvents()` is 92.93%

The test code of the smallest app causing the problem is below (mainly stolen from "GLFW Example code"). 
I also tried to test this in my real Vulkan app (with drawing etc.) - same results.
Tests were made in GLFW 3.2.1 under Windows 7 x64.

But if I create an OpenGL context and un-comment `glClear(...); glfwSwapBuffers(...);` - the CPU time drops to 0-1% immediately.

It seems there's a problem in `glfwPollEvents()`.

```
#define GLFW_INCLUDE_VULKAN 
#include <GLFW/glfw3.h>

int main(void) {
	GLFWwindow* window;

	/* Initialize the library */
	if (!glfwInit())
		return -1;

	glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API); // required for Vulkan

	/* Create a windowed mode window and its OpenGL context */
	window = glfwCreateWindow(640, 480, "High CPU load on Vulkan", NULL, NULL);
	if (!window) {
		glfwTerminate();
		return -1;
	}

	// Do not need to call this routine in Vulkan app
	// glfwMakeContextCurrent(window);

	/* Loop until the user closes the window */
	while (!glfwWindowShouldClose(window)) {
		// Do not need to call these routines in Vulkan app
		// glClear(GL_COLOR_BUFFER_BIT);
		// glfwSwapBuffers(window);

		/* Poll for and process events */
		glfwPollEvents();
	}

	glfwTerminate();
	return 0;
}
```

**Comment by tombsar** [comment]
Hi @hsa-online,

This is expected behaviour. The "poll" in the function name means that it should check to see if any events need processing, and return immediately otherwise. Since your loop has nothing else in it, your example program just spends all its CPU time checking for events over and over again. Using `glfwWaitEvents` instead should also give a dramatic drop in CPU usage.

**Comment by hsa-online** [comment]
Hi @tombsar,

Thank you for your answer.
But in real code the loop looks like this one:

```
while (!glfwWindowShouldClose(window)) {
	drawFrame();
	glfwPollEvents();
}
```

And in the `drawFrame()` there are many Vulkan calls like 
`vkWaitForFences(...), vkAcquireNextImageKHR(...), vkQueueSubmit(...), vkQueuePresentKHR(...)` and etc.

So logically my `drawFrame()` code should be equivalent to 
```
glClear(GL_COLOR_BUFFER_BIT);
glfwSwapBuffers(window);
```
because OpenGL code just draws nothing but Vulkan code draws triangles.

And because the real main loop isn't empty I see only one explanation to this: 
_the Vulkan code is so fast that it doens't have any influence to the main loop_. 

What do you think?

**Comment by tombsar** [comment]
There's one thing you can do to check what's going on, and that's to measure how many times the loop runs per second, and how long is spent in each of the `drawFrame` and `glfwPollEvents` functions (just use `glfwGetTime` for a rough estimate). I can believe that if you are only drawing very few triangles, the Vulkan calls take very little time on your thread.

I suspect the reason the OpenGL version shows so much less CPU usage is that `glfwSwapBuffers` is blocking until the next vsync interval, and the 16ms pause is not counted as active CPU time. I don't know Vulkan well enough, but it is possible that you are not locked to the monitor refresh rate, and running the loop 1000s of times per second, instead of 60.

**Comment by hsa-online** [comment]
I re-checked the app and found that the drawing logic really works extremely fast so it doesn't consume any significant amount of time.
And to get same results as I had in OpenGL version of app I changed the present mode value to VK_PRESENT_MODE_FIFO_KHR (at the swap chain creation stage).

Thank you!
