### ISSUE TITLE
Limit framerate

### ISSUE THREAD

**Issue by Memequickie** [glfw/glfw#1308]
While I was making game i needed to limit framerate to about 15fps. I tried to call `glfwWindowHint(GLFW_REFRESH_RATE, 15);`. No changes. 

Can anyone help? It may be related to opengl or my main loop.

**Comment by tombsar** [comment]
Hi @Memequickie The `GLFW_REFRESH_RATE` hint won't be much use, because it would be asking your monitor to switch to a mode with only 15Hz, which is unlikely to be supported. It also only applies to fullscreen apps, not windowed mode.

OpenGL will also not help you do framerate limiting; this is something you need to enforce with your main loop. You should probably look into articles for game programming that describe techniques for controlling game "tick" frequency, because this isn't one simple answer.

A very basic rate limiter would look something like this:
```
while (!glfwWindowShouldClose(window)) {
    double lasttime = glfwGetTime();
    myGameUpdate();
    while (glfwGetTime() < lasttime + 1.0/TARGET_FPS) {
        // TODO: Put the thread to sleep, yield, or simply do nothing
    }
    lasttime += 1.0/TARGET_FPS;
}
```

**Comment by Memequickie** [comment]
Thank you. That fixed my problem.
