### ISSUE TITLE
Event waiting with no windows documentation / code discrepancy

### ISSUE THREAD

**Issue by dougbinks** [glfw/glfw#1317]
Currently the [event processing documentation states](http://www.glfw.org/docs/latest/input_guide.html#events) that:

 *Even when you have no windows, event polling needs to be done in order to receive monitor connection events*.

However the code for both [glfwWaitEvents()](https://github.com/glfw/glfw/blob/master/src/window.c#L1075-L1083) and [glfwPostEmptyEvent()](https://github.com/glfw/glfw/blob/master/src/window.c#L1101-L1109) require a window present to work. This should likely either be documented or fixed. See [this thead on event loops without windows](http://discourse.glfw.org/t/single-event-loop-thread/1162/3) for reasoning behind why it might be preferable to handle this by making the event loop work without windows if this is possible on all platforms.

This appears to be related to issue #1281.

I would be able to handle the windows implementation, but am not familiar enough with the other backend event processing (I know it's a bit of a minefield from experience) if a fix is desired.

**Comment by elmindreda** [comment]
The weird behavior of `glfwWaitEvents` being a no-op without windows was due partly to GLFW at that time not having hidden helper windows on platforms where events can only be received via windows, and partly because AppKit wasn't being initialized until window creation and I didn't yet feel confident modifying the semi-undocumented way GLFW does that.

With 88c5edb40925bc0c987e8cfc7d306174f8094453 and ea7eb2ddab823e21c846c68d112d90f91fcba318 those issues should be resolved, so I would be in favor of dropping that behavior from `glfwWaitEvents` and `glfwPostEmptyEvent` in 3.3.

**Comment by elmindreda** [comment]
> However the code for both glfwWaitEvents() and glfwPostEmptyEvent() require a window present to work.

This requirement has now been removed with 55b1a16f9061520724fc507a9ef243f641d1ee02. Thank you!
