### ISSUE TITLE
glfwPollEvents is slow on El Capitan, glfw 3.2.1

### ISSUE THREAD

**Issue by ysmolsky** [glfw/glfw#1319]
`glfwPollEvents` takes more than 3 milliseconds when I hold any keys pressed, otherwise it takes less than 0.1 millisecond. 

I am able to reproduce this with `glfw 3.2.1` and `C` using the code:

```c
  /* Loop until the user closes the window */
  while (!glfwWindowShouldClose(window))
  {
    /* Render here */
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // Clear the buffers

    /* Swap front and back buffers */
    glfwSwapBuffers(window);

    /* Poll for and process events */
    double seconds = glfwGetTime();
    glfwPollEvents();
    seconds = glfwGetTime() - seconds;
    printf("%.7f\n", seconds);
  }
```

I get this when I hold any key pressed:
```
0.0030390
0.0013822
0.0031350
0.0000474
0.0034653
0.0000789
0.0036935
0.0000486
0.0041693
0.0000461
0.0031637
0.0000409
0.0034748
```
The original ticket was created for the Go wrapper, but it turned out that it's a problem with glfw, not the wrapper: https://github.com/go-gl/glfw/issues/223

**Comment by tombsar** [comment]
Are you able to repeat your test with the current master version of glfw? The 3.2.1 release is unfortunately quite outdated at this point.

**Comment by ysmolsky** [comment]
I have tried glfw built from the tip and got following:
```
0.1121638
0.0003263
0.0007464
0.0007603
0.0003149
0.0004046
0.0003503
0.0001074
0.0050350
0.0000862
0.0001003
0.0001273
0.0001201
0.0003292
0.0001168
0.0001043
0.0001226
0.0001234
0.0001267
0.0005690
0.0003003
0.0012206
0.0001185
0.0001406
0.0001288
0.0001357
0.0002516
0.0001711
0.0001507
0.0001511
0.0000981
0.0001480
0.0002858
0.0000684
0.0001902
0.0001041
0.0008783
0.0001284
0.0007442
0.0001711
0.0010496
0.0001105
0.0006938
0.0001162
0.0008243
0.0001118
0.0009663
0.0001124
0.0007114
0.0001259
0.0007345
0.0000872
0.0007651
0.0001200
0.0008655
0.0001170
0.0007336
0.0001176
0.0007739
0.0001037
0.0007207
0.0001277
0.0007025
0.0001177
0.0009670
0.0001107
0.0008772
0.0001160
0.0007348
0.0000999
0.0007679
0.0001133
0.0007062
0.0001087
0.0006997
0.0000822
0.0007666
0.0001024
0.0007447
0.0001071
0.0007119
0.0001330
0.0007692
0.0001141
0.0007074
0.0001215
0.0007131
0.0001501
0.0007646
0.0001117
0.0007481
0.0001033
0.0010014
0.0000895
0.0007629
0.0001520
0.0007176
0.0001297
0.0007117
0.0001057
0.0008064
0.0001192
0.0006948
0.0001213
0.0007295
0.0001160
0.0008463
0.0001258
0.0007640
0.0001020
0.0007117
0.0000864
0.0009748
0.0001148
0.0006938
0.0001006
0.0007409
0.0001029
0.0007749
0.0001107
0.0007024
0.0001084
0.0009462
0.0001184
0.0007395
0.0001340
0.0007260
0.0001046
0.0007219
0.0000966
0.0007787
0.0001242
0.0007482
0.0001138
0.0009736
0.0001236
0.0012609
0.0000955
0.0009034
0.0001188
0.0008853
0.0000805
0.0008722
0.0001081
0.0007152
0.0001084
0.0008477
0.0001045
0.0001469
0.0004346
0.0001105
0.0001214
0.0001360
0.0000960
0.0001033
0.0001159
0.0033061
```
It looks like there is an improvement to in latest version. Are these times look good to you as well?

**Comment by tombsar** [comment]
It certainly looks better, but I still see a few calls taking >1ms (not counting the first one) that I wouldn't be happy with. Can someone else with a Mac verify and profile this? I'm afraid I don't have access to any Apple machines.

**Comment by ysmolsky** [comment]
Here is the full listing and the way I built it:
```
~/tmp % cat glfwwindow.c
/* Ask for an OpenGL Core Context */
#define GLFW_INCLUDE_GLCOREARB
#include <stdio.h>
#include <GLFW/glfw3.h>

#define BUFFER_OFFSET(i) ((char *)NULL + (i))

int main(int argc, char** argv)
{
  GLFWwindow* window;

  /* Initialize the library */
  if ( !glfwInit() )
  {
     return -1;
  }

#ifdef __APPLE__
  /* We need to explicitly ask for a 3.2 context on OS X */
  glfwWindowHint (GLFW_CONTEXT_VERSION_MAJOR, 3);
  glfwWindowHint (GLFW_CONTEXT_VERSION_MINOR, 3);
  glfwWindowHint (GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  glfwWindowHint (GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
#endif

  /* Create a windowed mode window and its OpenGL context */
  window = glfwCreateWindow( 1280, 720, "Hello World", NULL, NULL );
  if (!window)
  {
     glfwTerminate();
     return -1;
  }

  /* Make the window's context current */
  glfwMakeContextCurrent(window);

  /* Loop until the user closes the window */
  while (!glfwWindowShouldClose(window))
  {
    /* Render here */
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // Clear the buffers

    /* Swap front and back buffers */
    glfwSwapBuffers(window);

    /* Poll for and process events */
    double seconds = glfwGetTime();
    glfwPollEvents();
    seconds = glfwGetTime() - seconds;
    printf("%.7f\n", seconds);

  }
  printf("%d %d\n", GLFW_VERSION_MAJOR, GLFW_VERSION_MINOR);

  glfwTerminate();
  return 0;
}
~/tmp % clang++ -std=c++11 -stdlib=libc++ -lglfw3 -framework CoreVideo -framework OpenGL -framework IOKit -framework Cocoa -framework Carbon glfwwindow.c
```
The revision of glfw it was built against: 8d3595fb

**Comment by tombsar** [comment]
Thanks for the detailed report.

Aside: `printf("%s\n", glfwGetVersionString());` is a little bit more useful than `printf("%d %d\n", GLFW_VERSION_MAJOR, GLFW_VERSION_MINOR);` because it contains more information.

For reference, running the same test on my Linux PC takes 11ms for the very first call, but subsequent calls to glfwPollEvents reliably take around 0.07ms (around 6x faster than your results).

**Comment by ysmolsky** [comment]
Thanks. I have fixed that line and the addition output is `3.3.0 Cocoa NSGL`

**Comment by ad8e** [comment]
I am not convinced your 3.3 slowdown is caused by glfw, because console output is expensive. You should push the times to a vector inside the loop, and then only output the vector's contents at the very end, after the loop is finished.

**Comment by ad8e** [comment]
Good. Here's what I learn from your data:

1. Something is sticking your timer to ~0.1ms resolution. On Windows/Linux, my C++ std::steady_clock timer is much finer. I haven't tried glfw's timer because C++'s <chrono> makes it obsolete, but I assume it works well too on Windows.
2. Your timer has 0.1ms frames but also some 0.5ms frames, and nothing in between. My first inclination is that this is because you're using glfwSwapInterval(1), but that won't lead to 0.5ms frames either, it'd give about 16ms. I don't really see why glClear would trigger on some frames but not others, but that seems like the most likely explanation.

**Comment by ysmolsky** [comment]
Kevin,
I measures only the pollEvents function there. And it does not handle vsync.

**Comment by ad8e** [comment]
Notice these lines in your code:

    glfwSwapInterval(1);


        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // Clear the buffers

        glfwSwapBuffers(window);

glClear maxes out at 400fps on my Windows computer at full resolution (it's dependent on window size). It's true there's no vsync happening but I think that is some Mac-specific API problem, because glfwSwapInterval(1) is telling glfw to ask for vsync.

**Comment by maxbennedich** [comment]
I'm also seeing slow `glfwPollEvents`, with glfw version "3.3.0 Cocoa NSGL EGL OSMesa dynamic" and macOS 10.14.3 (Mojave), especially when pressing any keys.

In my actual application, the call to `glfwPollEvents` averages ~0.75 ms (with individual calls taking up to 1.5 ms) when there's keyboard input (and 0.15 ms without input). As far as I can tell, it's not related to vsync. It is true that if I disable vsync, `glfwPollEvents` is much faster at ~0.15 ms with keyboard input, but my app also runs at ~420 fps instead of 60 fps, so presumably there are a lot fewer events to process. If I run without vsync, but manually sleep to get to 60 fps, `glfwPollEvents` is back at an average of ~0.75 ms. Also, if I vsync at 30 fps, the average call time is > 1 ms, again suggesting that a higher volume of events makes the call slower.

It might not seem like much, but if I aim for 60 fps, I have a total of ~16.7 ms per frame, so an extra 1.5 ms could easily cause a dropped frame here and there.

Here's what the output looks like for the program posted above during keyboard input:
```
0.0009666
0.0000643
0.0012079
0.0000525
0.0011273
0.0000507
0.0013552
0.0000321
0.0011501
0.0011805
0.0000462
0.0000564
0.0011172
0.0011773
0.0000456
0.0010903
...
```
If I change to `glfwSwapInterval(2)` (30 fps), the timings vary a lot more:
```
0.0028471
0.0022213
0.0002275
0.0002053
0.0002067
0.0044636
0.0011145
0.0027968
0.0023492
0.0002326
0.0002372
0.0031837
0.0005049
0.0003585
0.0001740
0.0105105
0.0022056
0.0000471
0.0004591
...
```

**Comment by ad8e** [comment]
> In my actual application, the call to `glfwPollEvents` averages ~0.75 ms (with individual calls taking up to 1.5 ms) when there's keyboard input (and 0.15 ms without input). As far as I can tell, it's not related to vsync. It is true that if I disable vsync, `glfwPollEvents` is much faster at ~0.15 ms with keyboard input, but my app also runs at ~420 fps instead of 60 fps, so presumably there are a lot fewer events to process. If I run without vsync, but manually sleep to get to 60 fps, `glfwPollEvents` is back at an average of ~0.75 ms. Also, if I vsync at 30 fps, the average call time is > 1 ms, again suggesting that a higher volume of events makes the call slower.

I disagree with your interpretation. My guess is that Vsync/sleep() is letting your CPU or OS fall to an idle state. When your CPU is pegged at 100%, this idle state doesn't occur and hence you get consistent 0.15 ms. I think higher event quantities is not the cause. You can test this by simulating 60 fps by polling events every 10000th iteration of the loop. This keeps your CPU busy, but still polls events at 60 fps.

**Comment by maxbennedich** [comment]
Ah, good point. I think you're right. Polling every 16th iteration simulates 60 fps with full CPU usage on my system, at which point `glfwPollEvents` averages only ~0.04 ms during keyboard input, and ~0.02 ms without. Negligible either way. Thanks for clarifying.

**Comment by tombsar** [comment]
Can this issue be closed?

**Comment by ysmolsky** [comment]
I do not think it's actionable. I have never tested the new version though. Closing for now.

**Comment by tombsar** [comment]
Thanks. Please reopen or file a new issue if you are still impacted by it.
