### ISSUE TITLE
Some glfw functions don't work immediatly after creating a window unless a sleep is added before them

### ISSUE THREAD

**Issue by Alex-----** [glfw/glfw#1375]
On linux (x11 and wayland, I haven't tested mac) some functions don't seem to work if they are called right after creating the window (or maybe just at the start of the program / after glfwInit?). The ones that are not working for me are glfwMaximizeWindow, glfwSetWindowMonitor, and glfwSetWindowAttrib(GLFW_FLOATING, GLFW_TRUE).

Also, I'm not able to redecorate a window with glfwSetWindowAttrib after removing decorations at any time (maybe this should be a different bug?).

My OS is Ubuntu 18.04.1 with GNOME 3.28.2. On Windows 10 all of the above functions work correctly. I'm using the latest release (nightly build from 12 days ago, LWJGL 3.2.1 SNAPSHOT build 9) of LWJGL (https://github.com/LWJGL/lwjgl3) which says it is using GLFW 3.3.0 pre-release.

Here's what some of my code looks like:

```java
window = checkWindow(glfwCreateWindow(p.width, p.height, title, NULL, BASE_WINDOW));
glfwSetWindowPos(window, p.x, p.y);
boolean linux = Platform.get() == Platform.LINUX;
if(maximized) {
	if(!linux) {
		glfwMaximizeWindow(window);
	} else {
		CompletableFuture.runAsync(() -> {
			Threads.sleep(500);
			eventHandler.run(() -> glfwMaximizeWindow(window));
		});
	}
}
if(images != null) glfwSetWindowIcon(window, images);
if(visible) glfwShowWindow(window);
initGLFW();
if(t != null) {
	if(!linux) {
		toggleFullscreen(t);
	} else {
		Monitor.Mode ft = t;
		CompletableFuture.runAsync(() -> {
			Threads.sleep(1000);
			eventHandler.run(() -> toggleFullscreen(ft));
		});
	}
}
```

**Comment by S-Marais** [comment]
this is mostly a Gtk problem, this also happens if you try to use gtk directly.

**Comment by elmindreda** [comment]
Many window functions like floating and maximization are handled by the window manager and requested by sending asynchronous events. What you are observing is likely the WM not having had time to fulfill the request.

**Comment by elmindreda** [comment]
The delay in updating some window attributes on X11 is because it involves three processes, all working asynchronously at least some of the time; the application, the X server and the window manager (and possibly also a separate compositing manager). There is often no mechanism for being notified that a window manager request has been completed and it is often free to ignore a request altogether, or to reinterpret it.

There have been fixes to the toggling of window decorations on X11 since this issue, which hopefully covers this case.
