### ISSUE TITLE
Allow custom EGL Display attributes

### ISSUE THREAD

**Issue by 333444555** [glfw/glfw#1380]
Is it possible to have a way to set custom EGL Display attributes before we create window, perhaps make it available through **glfw3native**? I need such feature to have **Google's ANGLE** use D3D9 instead of D3D11.
Is my only hope to rebuild with the display attributes?

**Comment by elmindreda** [comment]
It is absolutely possible. Will look into this for 3.4.

**Comment by elmindreda** [comment]
With 0dea8a4441828311af4c31de8ba798ba330c4755 one can now request a specific ANGLE rendering backend via the `GLFW_ANGLE_PLATFORM_TYPE` init  hint. Is that sufficient for your needs?

**Comment by 333444555** [comment]
It should do the job, thanks a lot for this.

**Comment by elmindreda** [comment]
Yay!

Also, as I said in #1718, if there are any specific attributes from those extensions that you also need to set, please let me know. There were too many of them in total for me to want to expose all of them just in case, and since I'm only a sporadic ANGLE user I wouldn't necessarily be able to pick the important ones.
