### ISSUE TITLE
Segmentation fault in glfwTerminate() if global namespace contains variable with name "close"

### ISSUE THREAD

**Issue by PixelOfDeath** [glfw/glfw#1397]
Defining any variable with the name "close" in global namespace causes segmentation fault when calling glfwTerminate().

Tested with latest git version of glfw. On Xubuntu 18.04 LTS (gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0)

**Comment by GreenLightning** [comment]
You are redefining the [close](http://man7.org/linux/man-pages/man2/close.2.html) symbol, which is already used for a linux system call.

**You most likely do not want to do that and as far as I'm aware there is no way that this can be fixed in glfw** (and this will cause issues with all other libraries that use file descriptors as well).

If you only use this variable in one file, you could make it `static` or put it into an [unnamed namespace](https://en.cppreference.com/w/cpp/language/namespace#Unnamed_namespaces) (if you are using C++). I believe this should resolve the problem.

Otherwise please rename your variable. If you `#include <unistd.h>` you should get a proper compiler error for the redeclaration.

**Comment by PixelOfDeath** [comment]
I see, the linker uses the first definition of that name for the function pointer. I'm kind of surprised it does not cause a linking error.
