### ISSUE TITLE
Vulkan API swapchain creation

### ISSUE THREAD

**Issue by elviras9t** [glfw/glfw#1436]
I suggest to add Vulkan API SwapChain management (native properties, sub-passes, probably create images, image count, multi-sampling) into GLFW3, but memory management (allocation, binding, using images) give to programmer care, or make Vulkan API management callbacks support (when resizing, when need allocate, when need change and use image). Shortly, make almost like OpenGL version, but configurable.

**Comment by tombsar** [comment]
Can you give any examples of hypothetical glfw API calls that you would like to see added? I'm not sure what we could do that was not just wrapping Vulkan API calls, and that is imo out of scope for this library.

**Comment by elviras9t** [comment]
``` // pseudo-code
glfwSetSurfaceDevice(window, vkdevice);
glfwPrepareSwapchain(window, &imageCreateInfo); // get image create info for allocation
// create images for swapchain
// ...
// set images
glfwSetImages(window, images);
glfwCreateSwapchain(window);

VkSwapChainKHR swapchain;
glfwGetSwapchain(window, &swapchain);

while (!glfwWindowShouldClose(window))
{
    VkImage image;
    glfwGetSwapchainImage(window, &image);
    // .. drawcalls
    glfwSwapBuffers(window, semaphore); // with waiting semaphore
    glfwPollEvents();
}
```

**Comment by CaffeineViking** [comment]
Yeah, I also agree with @tombsar on this, and feel that it's probably out of scope for GLFW. However, if we do get around to something like this, it would be cool to also be able to detect when recreating the swapchain is needed e.g. with `glfwSetSwapchainRecreationCallback`, since a bunch of Vulkan things (e.g. pipelines) need to be recreated as well (and it's not just a case of looking at a resize, there are other things that can happen).

**Comment by elmindreda** [comment]
Agreed, swapchain creation helper functions are outside the scope of GLFW.
