### ISSUE TITLE
glfwGetKeyName reports incorrect key strings

### ISSUE THREAD

**Issue by r00ster91** [glfw/glfw#1462]
I'm having quite some issues with `glfwGetKeyName`.
My keyboard layout is QWERTZ, the country Germany and the language German.
```c
#include <GLFW/glfw3.h>
#include <stdlib.h>
#include <stdio.h>

void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{
    printf("Key: %i, Scancode: %i\n", key, scancode);
    printf("glfwGetKeyName: %s\n\n", glfwGetKeyName(key, scancode));
}

int main()
{
    GLFWwindow* window;

    /* Initialize the library */
    if (!glfwInit())
        return -1;

    /* Create a windowed mode window */
    window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
    if (!window)
    {
        glfwTerminate();
        return -1;
    }

    /* Register a callback */
    glfwSetKeyCallback(window, key_callback);

    /* Loop until the user closes the window */
    while (!glfwWindowShouldClose(window))
    {
        /* Poll for and process events */
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}
```

Here's a list of keyboard keys on my keyboard (no caps lock) and their output of the above program, all of the outputs are incorrect:

* <kbd>-</kbd>
  ```
  Key: 47, Scancode: 61
  glfwGetKeyName: /
  ```

* <kbd>ß</kbd>
  ```
  Key: 45, Scancode: 20
  glfwGetKeyName: -
  ```

* <kbd>`</kbd>
  ```
  Key: 61, Scancode: 21
  glfwGetKeyName: ▒
  ```

* <kbd>ä</kbd>
  ```
  Key: 39, Scancode: 48
  glfwGetKeyName: ▒
  ```

* <kbd>ö</kbd>
  ```
  Key: 59, Scancode: 47
  glfwGetKeyName: ▒
  ```

* <kbd>ü</kbd>
  ```
  Key: 91, Scancode: 34
  glfwGetKeyName: ▒
  ```

All other key outputs are correct or are `null`.

The terminal I'm using (MobaXterm) is able to display all of these characters when I type them in the terminal.

Operating system: Windows 10, 64-bit
GLFW version string: 3.2.1 X11 GLX EGL clock_gettime /dev/js Xf86vm shared
I'm using the Windows Subsystem for Linux.

Can anyone else reproduce this?

**Comment by ghuser404** [comment]
@r00ster91 Any chance you can try this on the latest master?

**Comment by r00ster91** [comment]
Sorry, I forgot testing this on master. I just tried it in 3.3 and I can still reproduce this.

**Comment by db47h** [comment]
This also happens with a french keyboard layout with GLFW 3.2.1 and master. Calling `glfwGetKeyName(GLFW_KEY_1, 10)` yields `1` instead of `&`. 

I remember that this was working fine when #981 got closed. So I reverted to 8597002a177beb56db09cd1a9fca0025687dc706 and tested again: same issue. Looks like this is caused by an environment change (Ubuntu 16.04 -> 18.04) rather than a breaking change in GLFW.

**Comment by db47h** [comment]
The problem is here:

https://github.com/glfw/glfw/blob/d834f01ca43c0f5ddd31b00a7fc2f48abbafa3da/src/x11_window.c#L2802 

The `group` argument is not necessarily 0.  The actual fix is to add a `group` field in _glfw.x11.xkb:

```C
XkbStateRec state;
if (XkbGetState(_glfw.x11.display, XkbUseCoreKbd, &state) == Success)
    _glfw.x11.xkb.group =  state.group;
```

Then use that value in the call to `XkbKeycodeToKeysym`. 

I have multiple keyboards configured and depending on which is selected, the group changes. (I do not know if this is a new behavior compared to Ubuntu 16.04). However, anyone testing this will not necessarily see it break, depending on which keyboard is first.

The group value should be tracked and updated when the keyboard layout changes. See https://www.x.org/releases/X11R7.6/doc/libX11/specs/XKB/xkblib.html#determining_keyboard_state and the flowing topic. This would also be a step forward to implementing #1201).

**Comment by db47h** [comment]
Here's a working fix: https://github.com/db47h/glfw/commit/5796f163c7ae5af03cdc81c402f5fc6f37abd757

At least it works for me on Ubuntu 18.04.

**Comment by gracicot** [comment]
@db47h I already saw someone with an azerty and a qwerty keyboard plugged in. The two keyboard had both different layout. It was on X11

**Comment by db47h** [comment]
And to make things worse, there's no way to choose which device to query with `glfwGetKeyName()`. I'm not sure how to handle this correctly.

**Comment by db47h** [comment]
After putting some more thought into it, and keeping in mind that the 3.x API cannot be changed, an ok-ish solution to this is that `glfwGetKeyName` should return the key name for the default keyboard (`XkbUseCoreKbd`). The state change event handler also only tracks changes for this device.

So https://github.com/db47h/glfw/commit/5796f163c7ae5af03cdc81c402f5fc6f37abd757 should work for most users. For those with multiple keyboards, key callbacks will trigger for any keyboard, but it will still be impossible to query the actual key name for secondary keyboards. 

@elmindreda do you want me to submit a PR with this?

In order to address these kind of issues in GLFW 4.0, I believe that the proper course of action is to implement raw keyboard events like SDL does: have a a well defined scancode enumeration common to all platforms (the platform specific GLFW event handler will map platform specific scancodes to these), and push that GFLW scancode (layout independent) + key name (layout dependent) to the application. That way, applications that are only interested in actual key positions, like games, can use only scancodes, while others can use the key names (for shortcuts for example where you want to use layout dependent key names). Mapping scancodes to key names outside of event handlers will still be problematic in a multiple keyboard scenario, but I don't see it as a really serious problem.

**Comment by elmindreda** [comment]
@db47h Good work, please do submit a PR!

**Comment by db47h** [comment]
@elmindreda here you go. Could this be backported in a 3.3 minor release ?

**Comment by elmindreda** [comment]
@db47h Yes, absolutely.
