### ISSUE TITLE
glfwFreeCallbacks does not free joystick callback

### ISSUE THREAD

**Issue by DesertCookie** [glfw/glfw#1465]
I'm calling `glfwFreeCallbacks` before destroying my windows and it is successful at freeing all callbacks I've set (mostly for input), except the `JoystickCallback`; this callback has to be manually freed. Is this expected behavior, a bug or a problem with LWJGL?

_I am using GLFW through LWJGL and am debugging it using LWJGLx._

**Comment by Spasi** [comment]
It is expected behavior, `glfwFreeCallbacks` frees only callbacks associated with the `GLFWwindow` passed to it. Global callbacks (error, monitor, joystick) must be freed separately.

Btw, this question is off-topic here, `glfwFreeCallbacks` is a utility method in LWJGL that doesn't exist in GLFW. It was created because callback management is painful in Java.

**Comment by DesertCookie** [comment]
Thanks. Nothing in the docs hinted at it being GLFW proprietary (might want to add that?).
