### ISSUE TITLE
Screen tearing on 10.12 Sierra

### ISSUE THREAD

**Issue by jack1223233244** [glfw/glfw#1483]
There's a screen tearing issue on MacOS, Sierra. Tested on multiple Mac machines with the same results. Haven't been able to test it on other versions of MacOS. The issue persists both in windowed and fullscreen mode. No screen tearing with GLFW 3.21. Enabling multisampling seems to help. With swap buffer interval of 0 there's tearing on the whole screen. While at 1 tearing occurs exclusively at the lower parts of the screen.

**Comment by code-disaster** [comment]
I see similar results on a MacBook running 10.14.5. Enabling multisampling does not seem to have any effect in my case though.

**Comment by Adnn** [comment]
Same issue here with a Macbook pro running 10.14.6

My application (a simple grid scroller) is showing a lot of tearing around the bottom of the window. I cloned glfw and compiled at the _3.3_ tag to run the "Tests/tearing" application, and it shows extreme tearing too around the bottom.
The tearing actually gets wors as the swap_interval increases. Very surprisingly, there does not seem to be any tearing when the swap_interval is 0 (which should disable VSync, so it is strange). But as soon as the interval is set to 1 or more, the tearing becomes extremely noticeable.

Is there any progress on that front?

**Comment by Spasi** [comment]
@elmindreda LWJGL users have been suffering from tearing since the move to CVDisplayLink and there's finally been a breakthrough that you may find interesting. Start [here](https://github.com/LWJGL/lwjgl3/issues/503#issuecomment-551304662) (19c0307dcbb1f345fce0f8d5251e81310a6f798f has been tested as well).

**Comment by Adnn** [comment]
@Spasi Thank you for bringing hope back for macOS users! This tearing issue is very annoying at the moment, and would prevent any actual release on macOS targets.

Yet looking at the LWJGL thread you are linking to, as far as my limited understanding of the problem goes, it seems their conclusion is that building the JVM directly on their target platform solves all their issues. Is there some solution exportable to GLFW?

**Comment by Spasi** [comment]
@Adnn As far as I can tell, there are two workarounds and both are outside GLFW's scope:

1. The executable that starts the process is built on macOS 10.14 or higher.
2. `NSRequiresAquaSystemAppearance` is set to `No` in the application's `Info.plist`.

**Comment by void256** [comment]
Yes what @Spasi said and additionally:

If you are currently running 10.14+ and the executable was built with or before 10.13 then it is likely you’ll see screen tearing with or without the swap interval workaround applied. In this case just building the executable with 10.14+ seems to fix the issue in both cases.

However, the original post had a problem with running on 10.12 which might not be related to the issue we discovered :/ (since what we found was especially a check for “was built on 10.14 or later otherwise do something else”)

**Comment by elmindreda** [comment]
Hopefully OpenGL swap interval is usable again now. If it is then 3.3.1 is ready for release.
