### ISSUE TITLE
GLFW and Java AWT

### ISSUE THREAD

**Issue by ws909** [glfw/glfw#1645]
Calls to `java.awt.SystemTray.isSupported();` make subsequent calls to `glfwPollEvents()`, `glfwWaitEvents()` and `glfwWaitEvents(long)` never return, but still execute callbacks on demand, as if the program control has been moved to another loop. 

```java
import java.awt.*;
import static org.lwjgl.glfw.GLFW.*;

public class TEST {
    
    public static void main(String[] args) {
        
        glfwInit();
        
        var window = glfwCreateWindow(100, 100, "buggy", 0, 0);
    
        glfwSetKeyCallback(window, ($, key, scancode, action, mods) -> {
            if (action == GLFW_PRESS) {
                System.out.println("key = " + key + "; scancode = " + scancode + "; mods = " + mods);
            }
        });
    
        SystemTray.isSupported();
    
        glfwShowWindow(window);
        
        while (true) {
            System.out.println("A");
            
            glfwPollEvents();
            
            System.out.println("B");
        }
    }
}
```

This example has been tested and verified in OpenJDK 13, LWJGL 3.2.3, on MacOS 10.14.5 Mojave. No error messages are printed.

**Comment by TheMrMilchmann** [comment]
> as if the program control has been moved to another loop

Precisely! This is exactly what's happening. However, this is not an issue with GLFW (or AWT) but a limitation of MacOS in general since, basically, the only thread with access to the window system is the main thread and AWT starts it's internal event loop on initialization. Workarounds exist for some problems, but the general recommendation is to avoid using AWT on MacOS with LWJGL 3.

Read more:
- lwjgl/lwjgl3#68
- lwjgl/lwjgl3#306
- lwjgl/lwjgl3#311

**Comment by ws909** [comment]
Thanks. I should've searched LWJGL's repository in advance, I see.
I'm gonna have to find another way to deliver user notifications, then, in a cross-platform way.
