### ISSUE TITLE
GLFW mouse click delay due on MacOS due to Magnet app

### ISSUE THREAD

**Issue by jkrumbiegel** [glfw/glfw#1665]
This issue drove me crazy for a while, on MacOS I experienced long delays (100s of milliseconds) until mouse clicks were registered in my program (using the packages Makie.jl / GLFW.jl in Julia). The culprit, as I found out today, is the app Magnet, the issue was gone once I closed it. I spent a long time trying to debug this, so I'll leave this here in case other people are looking for the same thing.

**Comment by elmindreda** [comment]
Thank you!

**Comment by nmwsharp** [comment]
In 2025 this is still the case! Just spent a very long time debugging some weird mouse latency issues that turned out to be due to Magnet running, and shutting-down Magnet resolves the issue. The symptom was a consistent, ~5 frame delay, but _only_ for left mouse presses (all other events were fine).

However, I wonder if there actually might be a sneaky GLFW bug here. When I use a simple test app that processes events via pure native Cocoa/NSEvent, there is no problem and no lag. But a simple GLFW test app _does_ give lag. So maybe there is some obscure problem with GLFW event processing, and Magnet just happens to be the way to trigger it. Attaching some info in case anyone ever wants to debug. (I don't have permissions to reopen the issue)


Some more details:
- observed on MacOS Sequoia 15.3.1 
- GLFW version 3.4
- GLFW code: simple example loop that create a window, sleep's the framerate to 10fps (so the delay is noticeable) and prints on left-click
- Cocoa code: (inline below)

```
#import <Cocoa/Cocoa.h>
#include <stdio.h>

int frame_count = 0;

@interface AppDelegate : NSObject <NSApplicationDelegate>
@property (strong) NSWindow *window;
@property (strong) NSTimer *frameTimer;
@end

@implementation AppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)notification {
    // Create a simple window
    NSRect frame = NSMakeRect(100, 100, 400, 300);
    self.window = [[NSWindow alloc] initWithContentRect:frame
                                              styleMask:NSWindowStyleMaskTitled | NSWindowStyleMaskClosable
                                                backing:NSBackingStoreBuffered
                                                  defer:NO];
    [self.window setTitle:@"Raw Mouse Event Test"];
    [self.window makeKeyAndOrderFront:nil];

    // Add event monitors for mouse clicks
    [NSEvent addLocalMonitorForEventsMatchingMask:NSEventMaskLeftMouseDown
                                          handler:^NSEvent*(NSEvent* event) {
        printf("Frame %d: Raw Cocoa LEFT click\n", frame_count);
        return event;
    }];

    [NSEvent addLocalMonitorForEventsMatchingMask:NSEventMaskRightMouseDown
                                          handler:^NSEvent*(NSEvent* event) {
        printf("Frame %d: Raw Cocoa RIGHT click\n", frame_count);
        return event;
    }];

    // Start a timer to simulate frame counting (10 FPS)
    self.frameTimer = [NSTimer scheduledTimerWithTimeInterval:1.0/10.0
                                                      repeats:YES
                                                        block:^(NSTimer * _Nonnull timer) {
        frame_count++;
    }];

    printf("Click in the window with left and right mouse buttons...\n");
}

- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(NSApplication *)sender {
    return YES;
}

@end

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSApplication *app = [NSApplication sharedApplication];
        AppDelegate *delegate = [[AppDelegate alloc] init];
        [app setDelegate:delegate];
        [app run];
    }
    return 0;
}

```
