### ISSUE TITLE
drag window is laggy initially on macOS

### ISSUE THREAD

**Issue by changkun** [glfw/glfw#1797]
I just got the initial example up and running, and created a window tested on macOS and Linux. 

```c
#include <GLFW/glfw3.h>

int main(void)
{
    GLFWwindow* window;

    /* Initialize the library */
    if (!glfwInit())
        return -1;

    /* Create a windowed mode window and its OpenGL context */
    window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
    if (!window)
    {
        glfwTerminate();
        return -1;
    }

    /* Make the window's context current */
    glfwMakeContextCurrent(window);

    /* Loop until the user closes the window */
    while (!glfwWindowShouldClose(window))
    {
        /* Render here */
        glClear(GL_COLOR_BUFFER_BIT);

        /* Swap front and back buffers */
        glfwSwapBuffers(window);

        /* Poll for and process events */
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}
```

The problem is:

If I drag the window and move around, the movement of the window feels laggy initially but gets smoother later on (see the window jumps when I drag in the figure below). The issue does not appear on Linux (Ubuntu). Why and how to fix it?

![5EXtj](https://user-images.githubusercontent.com/5498964/97170578-3828f280-178c-11eb-882d-ac94d1b74379.gif)

System: macOS 10.15.7 (19H2)

**Comment by tombsar** [comment]
Does it still lag if using `glfwWaitEvents` instead of `glfwPollEvents`?

**Comment by changkun** [comment]
@tombsar Thanks for the hint. The lag is gone after switch to `glfwWaitEvents`! What's the reason? Perhaps it would be great to update the official document that explains which call should be used by default?

**Comment by tombsar** [comment]
`glfwPollEvents` processes events if there are any, otherwise returns immediately. That means your (trivial) program is clearing the screen over and over again as quickly as possible, consuming a lot of CPU time. The alternative, `glfwWaitEvents`, blocks if there are no events waiting, consuming little or no CPU time. Arguably a program using a lot of CPU should not cause the window to lag, but that's really down to the operating system and how it allocates resources.

As for which of the two functions to use, it depends entirely on what else you want your program to do. If you only want to react to user input, and nothing else, `glfwWaitEvents` is probably the way to go. If you want to do other things within the event loop, `glfwPollEvents` is probably more appropriate, especially if you want to redraw the window contents independently of user input.

Aside: `glfwSwapInterval(1)` will probably also avoid the lag, as it will cause `glfwSwapBuffers` to block for some milliseconds, again giving the CPU a rest.

**Comment by changkun** [comment]
@tombsar Thanks again for your detailed explanation. 

> As for which of the two functions to use, it depends entirely on what else you want your program to do. If you only want to react to user input, and nothing else, `glfwWaitEvents` is probably the way to go. If you want to do other things within the event loop, `glfwPollEvents` is probably more appropriate, especially if you want to redraw the window contents independently of user input.

This sounds a little bit tricky. Why developers must concern about this? Ideally, we would expect the program to react to user inputs as well as render content depending on the user inputs. But in some cases, we might also want to redraw regardless of user inputs. Are there any good examples that can leverage both? Or is it implicating we must manage the call to `glfwPollEvents` or `glfwWaitEvents` based on application status?

**Comment by tombsar** [comment]
> This sounds a little bit tricky. Why developers must concern about this?

It's a fairly common thing to think about when writing low-level code; sometimes you just want to check if something is waiting, other times you want to wait until there is.

Note that there is a third option, `glfwWaitEventsTimeout` (https://www.glfw.org/docs/latest/group__window.html#ga605a178db92f1a7f1a925563ef3ea2cf) that waits, but only for a limited amount of time. That might be the best option here, but it's hard to tell without knowing what you want your program to do!

Personally, I use `glfwWaitEvents` in my main application loop, and put rendering on a secondary thread, but that adds a fair bit of complication to the code.

**Comment by changkun** [comment]
@tombsar Understood, thank you so much @tombsar
