### ISSUE TITLE
Src folder reorganization into subfolders

### ISSUE THREAD

**Issue by llchris** [glfw/glfw#1854]
I think that sorting glfw's source files into subfolders based on their target platform would be a good idea so everytime someone compiles glfw manually doesn't have to remember which files to compile/include for each platform. 

Example: src/win32_init.c moved into src/win32/init.c 
src/x11_init.c  moved into src/x11/init.c

It's nothing important for the library, it would just save some time for me each time i create a new project with glfw

**Comment by elmindreda** [comment]
Agreed, it's a hassle for people setting up their own build system to get this right. This solution would be tricky, however, as several source files are shared between window systems, or picked based on the OS instead of the window system.

The solution I'm working on is to have the source files themselves figure this out, so you can even build `*.c` (and `*.m` if so inclined) and have it work. I'm closing this as won't fix but a fix for the annoyance is coming.
