### ISSUE TITLE
License implication due to xinput.h/dinput.h under LGPL?

### ISSUE THREAD

**Issue by not-an-error** [glfw/glfw#1906]
Hi,

I noticed that part of the dependencies of `glfw` are actually licensed under LGPL, specifically these two files:

* https://github.com/glfw/glfw/blob/master/deps/mingw/xinput.h
* https://github.com/glfw/glfw/blob/master/deps/mingw/dinput.h

Does this have any implication to the license of `glfw` itself?

Thanks!

**Comment by elmindreda** [comment]
I am not a lawyer. I believe our use of those files falls under the exception for declarations from header files in section 5 of the LGPL2.

**Comment by not-an-error** [comment]
Thanks a lot!

**Comment by Wilm0rien** [comment]
hi want to raise attention to this again.

we internally performed a black duck analysis and we failed because of [dinput.h](https://github.com/glfw/glfw/blob/master/deps/mingw/dinput.h)

the following obligations were put upon our software because of this:

> 1) Keep intact all notices (copyright, license, patent, trademark, disclaimers of warranty etc.)
> 2) Provide Attribution with
> 2.1) Name of Component
> 2.2) Copyright
> 2.3) License text
> 3) Provide source code of the OSS 
> Source code to be provided shall include the following:
> I. Source code of the LGPL library under the terms of LGPL license.
> II. Code for rest of the product in source code/binary form under a limited permission (by means > of a contract), so that the user can modify the LGPL Library and then re-link to produce a modified product executable (containing the modified LGPL Library).
> or
> OFFER TO PROVIDE SOURCE CODE
> Accompany the work with a written offer, valid for at least three years, to give the same user > the materials specified in Subsection 6a, above, for a charge no more than the cost of performing this distribution.
 > 
> Allow reverse engineering of the product for limited purpose of debugging modifications that user, may make to the library under LGPL. [Sec 6]
> 


is it correct that this issue basically breaks using glwf under zlib license as stated in LICENSE.md?

**Comment by elmindreda** [comment]
I stand by my reply above. Here is what I believe is the relevant part of the LGPL 2.1

>  When a "work that uses the Library" uses material from a header file that is part of the Library, the object code for the work may be a derivative work of the Library even though the source code is not. Whether this is true is especially significant if the work can be linked without the Library, or if the work is itself a library. The threshold for this to be true is not precisely defined by law.
> 
> If such an object file uses only numerical parameters, data structure layouts and accessors, and small macros and small inline functions (ten lines or less in length), then the use of the object file is unrestricted, regardless of whether it is legally a derivative work. (Executables containing this object code plus portions of the Library will still fall under Section 6.) 

The header files in `deps/mingw` are unmodified copies from MinGW-w64, bundled because MinGW doesn't provide them. They are only used at all when building on MinGW. If you delete them, the only change is that GLFW won't compile on MinGW. On MinGW-w64 and Visual Studio they are not even in the include path.

When we do use these headers we use only "numerical parameters, data structure layouts and accessors", in order to compile code directly calling the DirectInput and XInput APIs. We use no portion of any MinGW "library" because there is none. What we call is the corresponding Windows DLLs, loaded at runtime.

Those same headers with the same license are used whenever a program using those APIs is compiled with MinGW-w64.

**Comment by Wilm0rien** [comment]
Thanks a lot for the great response!
