### ISSUE TITLE
Window position uses content area origin

### ISSUE THREAD

**Issue by gnif** [glfw/glfw#2371]
GLFW fails to take into account the relative offset as per the X window attributes for the caption bar and/or borders. When a decorated window is set to position 0x0 the content area is positioned at 0x0, obscuring the caption bar.

The solution to this is to obtain the relative offset via `XGetWindowAttributes` `x` & `y` members and offset the window position by the value returned.

> The x and y members are set to the upper-left outer corner relative to the parent window's origin.

Ref: https://tronche.com/gui/x/xlib/window-information/XGetWindowAttributes.html

**Comment by elmindreda** [comment]
> GLFW fails to take into account the relative offset as per the X window attributes for the caption bar and/or borders. When a decorated window is set to position 0x0 the content area is positioned at 0x0, obscuring the caption bar.

That's true but this is by design. See [glfwGetWindowFrameSize](https://www.glfw.org/docs/latest/window#window_size) for the current extents of the window frame, and then [glfwGetMonitorWorkarea](https://www.glfw.org/docs/latest/monitor#monitor_workarea) for where the frame can be safely placed.

Speaking as someone who keeps taskbars on the top of the screen on every OS, please don't assume 0,0 is a good place to put a window.

**Comment by gnif** [comment]
> please don't assume 0,0 is a good place to put a window.
We do not, our application allows the user to specify a exact pixel position for the window coordinates as a launch arg based on their requirements.

> See [glfwGetWindowFrameSize](https://www.glfw.org/docs/latest/window#window_size)

Thanks, I had missed this API
