### ISSUE TITLE
No workaround for broken vsync on Aero

### ISSUE THREAD

**Issue by martinbis11** [glfw/glfw#24]
Under Windows, glfwSwapInterval() doesn't do anything if composition is enabled (see _glfwPlatformSwapInterval() in wgl_context.c) because it can cause some from jitter when sync is actually enabled.

It would be nice if it was possible to force use of VSync, even if composition is enabled.

**Comment by elmindreda** [comment]
This has received what may be a more appropriate fix with 8309e0ecb09fe5cf670dff5df1e7ca71821c27bd.

**Comment by softwarefailure** [comment]
Not a good fix for me. It works fine in windowed mode but in fullscreen mode my text scrollers that I want to be fully in sync with the vertical refresh are really stuttering now.

Besides that, I really think we need a fix for the problem that on OS X and Linux vsync is working properly and on Windows it isn't. Personally, I never experienced the infamous jitter that has caused the GLFW team to introduce the GLFW_USE_DWM_SWAP_INTERVAL flag. That's why I always define GLFW_USE_DWM_SWAP_INTERVAL. I've tested my project on lots of machines (XP, Vista, 7 and 8) and none showed the jitter. Still, I remain slightly worried because of the explicit jitter warnings expressed in the docs so I was happy to see a new approach here but as I said above, in fullscreen mode this new approach totally throttles my graphics now and makes them all stuttery.

**Comment by softwarefailure** [comment]
I've also posted about the vertical refresh sync issue on StackOverflow. See here:
http://stackoverflow.com/questions/30437756/glfwswapbuffers-and-vertical-refresh-on-windows/30438131

There's also some example code in that post.

**Comment by elmindreda** [comment]
@softwarefailure What graphics card do you have on your Windows machine?

**Comment by softwarefailure** [comment]
I have three different test machines. 

1) XP with a Radeon 9250
2) Vista with an ATI Mobility Radeon HD 2400 XT
3) Windows 7 with an AMD Radeon HD 6450

On machine 1 it's working correctly in both windowed and fullscreen mode. On machines 2 and 3 only windowed mode is good. In fullscreen mode the movement is clearly not smooth and there's some stuttering / refresh artifacts.

Here's the test code that I used:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <windows.h>

#include <GLFW/glfw3.h>

int main(void)
{
	GLFWwindow* window;
	int i = 0, mode = 0;
	GLFWmonitor **mons;
	int count;
			
	if(!glfwInit()) return -1;

 	mons = glfwGetMonitors(&count);
 
	window = glfwCreateWindow(640, 480, "Hello World", *mons, NULL);
	if(!window) {
		glfwTerminate();
		return -1;
	}

	glfwMakeContextCurrent(window);
	glfwSwapInterval(1);
	
	glMatrixMode(GL_PROJECTION);
 	glLoadIdentity();
 	glOrtho(0, 640, 0, 480, -1, 1);		
	glDisable(GL_DEPTH_TEST);
	glDisable(GL_BLEND);	
	glDisable(GL_TEXTURE_2D);	
	glMatrixMode(GL_MODELVIEW);
 	glLoadIdentity();
	
	glColor3f(1.0, 1.0, 1.0);
	
	while(!glfwWindowShouldClose(window)) {
		
		glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);
		glRecti(i, 190, i + 100, 290);		
		
		glfwSwapBuffers(window);
		glfwPollEvents();
		
		if(!mode) {
			i++;
			if(i >= 539) mode = 1;
		} else {
			i--;
			if(i <= 0) mode = 0;
		}			
	}

	glfwTerminate();
	
	return 0;
} 
```

It simply moves a white box from left to right and back again. The aim is to have it moving without any refresh artefacts. Currently this only happens on the XP machine. On Vista and 7 it's stuttering and there are some refresh artefacts in fullscreen mode. In windowed mode it works perfectly on all three systems.

**Comment by elmindreda** [comment]
If you have access to a machine with an Nvidia card, enable Aero and run the tearing test.

**Comment by elmindreda** [comment]
@softwarefailure Please open a new issue for this and we can continue there.

**Comment by softwarefailure** [comment]
@elmindreda: Unfortunately, I don't have a machine with an Nvidia card.

New issue has now been opened: https://github.com/glfw/glfw/issues/519
