### ISSUE TITLE
Is there a specific reason why `glfwGet/SetJoystickUserPointer` requires the joystick to be allocated?

### ISSUE THREAD

**Issue by GasimGasimzada** [glfw/glfw#2401]
I was trying to set a user pointer to the joystic; so, I can access it during callback:

```cpp
for (int jid = 0; jid <= GLFW_JOYSTIC_LAST; ++jid) {
  glfwSetJoystickUserPointer(jid, this);
}

glfwSetJoystickCallback([](int jid, int event) {
  auto *window = static_cast<Window *>(glfwGetJoystickUserPointer(jid));
});

```

This does not work if a joystic is not already present in the system. So, I was trying to understand why this limitation is in-place by going throught the source code and came across this line: https://github.com/glfw/glfw/blob/master/src/input.c#L1216. From my understanding, the `allocated` flag is set when creating reference to a [real joystic device](https://github.com/glfw/glfw/blob/master/src/input.c#L521). However, even in this allocation code, we are not overriding the joystic object but modifying fields of the joystick one-by-one.

So, it got me thinking. Is there a specific reason why we need to check whether a joystic is allocated when setting or getting a joystick? Because if we can get rid of this check and not clear the user pointer when freeing the joystick, we can store any user pointer to any joystick way before they are initialized and access the user pointers from callback instead of storing variables globally/statically to be able to access these values.

**Comment by elmindreda** [comment]
Joystick user pointers, the way they are currently implemented, are global variables. They don't become less global because they're stored by GLFW. If you want to store pointers globally independent of joystick connection lifetimes then make your own global variables.

GLFW 3 joysticks should have been fully independent objects, like windows and cursors instead of just IDs. However, it's still helpful to think of them as independent objects to make sense of things like the behavior of user pointers.

Joystick user pointers are intended to store application state specific to that connection of that joystick/controller/device, which is why they're tied to the lifetime of that connection, why you cannot set them before a joystick is connected to an ID and why the pointer is cleared again once the device is disconnected.

**Comment by GasimGasimzada** [comment]
Thank you for the reply! The reason why I was trying to utilize it was because I wanted to pass my class instance to `glfwSetJoystickCallback` and use that to enable/disable device usage in my game engine without needing to store the class instance as global. But I understand that it makes sense from API perspective since the joystics are global and not attached to a window. I ended up just storing the pointer to class instance as global and it solved the issue:

```cpp
static auto *DeviceManager= &mDeviceManager;
glfwSetJoystickCallback([](int jid, int event) {
  if (event == GLFW_CONNECTED) {
    DeviceManager->addDevice(InputDeviceType::Gamepad, jid);
  } else if (event == GLFW_DISCONNECTED) {
    DeviceManager->removeDevice(InputDeviceType::Gamepad,
                                        static_cast<u32>(jid));
  }
});
```

**Comment by elmindreda** [comment]
Looks good! Closing this as resolved.
