### ISSUE TITLE
gles 2 context creation with angle on windows fails without error

### ISSUE THREAD

**Issue by SeleDreams** [glfw/glfw#2413]
![image](https://github.com/glfw/glfw/assets/16335601/2515a903-12fd-44c8-acd0-34a5ecb037d1)
I've been trying to make my engine use gles 2 using angle, but I noticed that the functions from opengl didn't have any effect, whether I used glClear etc nothing happened, so i then checked glVersion and as you can see, the result is null even though my previous check shows that for glfw the context is valid.
the binary was properly linked with angle using `target_link_libraries(gl-graphics core-graphics core-maths glfw3 EGL GLESv2)`

Do you have any idea of where the issue could come from ? I am on windows 11 64-bit with an rtx 2080 GPU

**Comment by elmindreda** [comment]
Hi! I see you are calling `glfwWindowHint` before `glfwInit`. Calling `glfwWindowHint` before initialization will not do anything except generate `GLFW_NOT_INITIALIZED` errors. That means the context was created with WGL, which is why the `glGetVersion` call you make to the `GLESv2` library returns `NULL`. As far as your EGL knows, there is no current context.

**Comment by elmindreda** [comment]
I generally recommend developers set an [error callback](https://www.glfw.org/docs/latest/intro#error_handling) at least during development. GLFW has a lot of error description strings that try to explain what happened and that's the easiest way to get them delivered whenever there is an error.
