### ISSUE TITLE
Anyone else has rights to merge PRs ? Any news on elmindreda ? Should we create a new repo ?

### ISSUE THREAD

**Issue by Scr3amer** [glfw/glfw#2421]
Hello there !

I see PRs are starting to stack up. Do we have any news on the main maintainer ? Should we consider creating a new repo ?

Cheers,
Scr3am

**Comment by dougbinks** [comment]
I'm the GLFW forum admin and one of the contributors along with @siavashserver who maintains the website. I'm reaching out to @elmindreda to offer my assistance - I've been offered write permissions in the past but refused due to not having enough bandwidth at the time. This may take a bit of time so please be patient.

**Comment by dougbinks** [comment]
I'm now no the GLFW team and working with @elmindreda to resolve issues and PRs etc., so I'm going to close this issue to help clean things up.
