### ISSUE TITLE
`glfwGetWindowFrameSize` returns all zeros for decorated non-fullscreen window

### ISSUE THREAD

**Issue by akarampetsos** [glfw/glfw#2435]
OS and version: Fedora 38 Kinoite
Release or commit: 3.4.0

I was having some issues with the `glfwGetWindowFrameSize` function returning all zeros for a decorated non-fullscreen window.

Upon further debugging, I created a [demo repo](https://github.com/akarampetsos/glfw-frameSize-demo) to pinpoint when exactly it happens.
I am building version 3.4.0 straight from master with `GLFW_USE_WAYLAND=ON`.
When running with `GLFW_PLATFORM` init hint set to wayland, the frame size always returns all zeros.
When running with `GLFW_PLATFORM` init hint set to x11, the frame size returns zeros at first but after a Window Focused event, it returns the correct values.

I encountered this issue while using LWJGL, so I don't really know much C (or low level programming in general) but I would be happy to provide any further information needed. I hope I am not misreporting some intended behavior and if I am, sorry about that. The reporting guidelines also mentioned posting the events tool logs but I don't see how that can help in this issue. If it's needed, I can of course provide that.

Here are some logs from my demo:

* X11

```
Using x11
GLFW version: 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic
Before loop
Content area size (WxH): 800x600
Frame size (TxRxBxL): 0x0x0x0
Framebuffer size (WxH): 800x600
---
Focus changed: focused
Content area size (WxH): 800x599
Frame size (TxRxBxL): 31x0x0x0
Framebuffer size (WxH): 800x599
---
New framebuffer size (WxH): 800x599
Content area size (WxH): 800x599
Frame size (TxRxBxL): 31x0x0x0
Framebuffer size (WxH): 800x599
---
New window size (WxH): 800x599
Content area size (WxH): 800x599
Frame size (TxRxBxL): 31x0x0x0
Framebuffer size (WxH): 800x599
---
```

* Wayland

The first error doesn't trigger if position is not set but nothing else changes

```
Using wayland
GLFW version: 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic
GLFW Error 65548 | Wayland: The platform does not support setting the window position
GLFW Error 65548 | Wayland: The platform does not support setting the input focus
Before loop
Content area size (WxH): 800x600
Frame size (TxRxBxL): 0x0x0x0
Framebuffer size (WxH): 800x600
---
New framebuffer size (WxH): 1600x1200
Content area size (WxH): 800x600
Frame size (TxRxBxL): 0x0x0x0
Framebuffer size (WxH): 1600x1200
---
Focus changed: focused
Content area size (WxH): 800x600
Frame size (TxRxBxL): 0x0x0x0
Framebuffer size (WxH): 1600x1200
---
```

**Comment by akarampetsos** [comment]
Also noting, that sleeping for some seconds after showing the window and then calling `glfwGetWindowFrameSize` returns correct values on x11. Still zeros on wayland.

**Comment by elmindreda** [comment]
> When running with `GLFW_PLATFORM` init hint set to wayland, the frame size always returns all zeros.

This is a limitation of Wayland. There is no API for finding out the window frame size, so the only time GLFW has any knowledge of it is when using the most basic fallback decorations as those are drawn by GLFW itself.

Then again, on Wayland there is no API for setting or even finding out the absolute position of a top-level window either, so there isn't much use for the frame size anyway.

>When running with `GLFW_PLATFORM` init hint set to x11, the frame size returns zeros at first but after a Window Focused event, it returns the correct values.

Window frames only exist for visible windows on X11. There is a protocol for getting the frame size before a window is shown but some window managers don't implement it correctly[^1]. It's possible that if you retrieve the frame size right after creating the window that it hasn't actually been shown yet[^2] and GLFW then uses this protocol instead of the more straightforward query that can be used for visible windows.

Which window manager are you using on X11?

[^1]: It's an unnatural thing for window managers to do as they usually only deal with visible windows.

[^2]: X11 is very async and involves at least your program, the X server and the window manager. GLFW often doesn't wait until an action has been fully completed. partly for performance reasons but also because the window manager has the right to refuse or modify a lot of requests.

**Comment by akarampetsos** [comment]
Sorry for the late response!

> Which window manager are you using on X11?

KWin (KDE Plasma v5.27.8) with XWayland v22.1.9

> Then again, on Wayland there is no API for setting or even finding out the absolute position of a top-level window either, so there isn't much use for the frame size anyway.

I was about to respond that even though I read that in the documentation, to my surprise it worked but with a warning but I decided to double check. So scratch that, it turns out that the window already appears centered on wayland and that's why I mistakenly thought that my centering code was working on wayland too.

> Window frames only exist for visible windows on X11. There is a protocol for getting the frame size before a window is shown but some window managers don't implement it correctly. It's possible that if you retrieve the frame size right after creating the window that it hasn't actually been shown yet and GLFW then uses this protocol instead of the more straightforward query that can be used for visible windows.

I was not aware of that, that makes sense. I think I will just implement some custom blocking logic to wait for the window to be visible or abandon the idea of setting the window positions altogether (I was trying to create a grid of windows, which would require knowing the size and setting the position).

I appreciate the help, thank you!
