### ISSUE TITLE
Weird memory allocations in glfwSwapBuffers

### ISSUE THREAD

**Issue by kayoscode** [glfw/glfw#2451]
```
   // Called during the render sequence.
   static void DrawFrame(wgui::WindowBase* window, GLFWwindow* gWin, nk_glfw* nkGlfw, wgui::WindowRenderer* layoutRenderer)
   {
      glfwSwapBuffers(gWin);
   }


   // Executing on separate thread.
   static void ExecuteRenderLoop(wgui::WindowBase* mainWindow, GLFWwindow* gWin)
   {
      glfwMakeContextCurrent(gWin);

      while (!mainWindow->Closing())
      {
         mainWindow->Render();
      }
   }
```

The main thread is calling poll events constantly.

![image](https://github.com/glfw/glfw/assets/24443205/afa77b18-e936-4555-9759-f0215c2990be)

Resizing the window causes massive spikes in memory usage despite not doing anything else except swapping the buffers.

**Comment by youngbrycecode** [comment]
Doing some more experimentation, I was unable to locate where the actual allocation is done since it appears to be in swapBuffersWGL(_GLFWwindow*) { ... SwapBuffers) which is not something I can step into or see the source code for. I took the update off thread since I don't even know if I did that right and while it no longer overwhelms the memory instantly, every time it draws a frame after a resize, it allocates a few megabytes of memory and does not return it.

**Comment by youngbrycecode** [comment]
I appears to be an issue with the interaction between glfw and the nahimic service. Not sure what to do about it though since users who install the program will crash if they have the service

**Comment by elmindreda** [comment]
Thank you for digging into this!
