### ISSUE TITLE
Attach of debugger causes duplicated application launch in Xcode 16

### ISSUE THREAD

**Issue by endanke** [glfw/glfw#2634]
We are building and running a command line application target, which launches an application window **using GLFW**.
After upgrading to Xcode 16, we started to notice an issue when debugging is enabled for the target.

Right after the launch of the application, a secondary instance is launched which is an unexpected behaviour.

The issue is not reproducible if an application window wasn't created.
A temporary workaround is to add a 1 second delay to the main function of the software, which also prevents the unnecessary secondary instance launch, however we don't want to unconditionally wait in our software.

If the "debug executable" option is disabled for the scheme, the secondary instance is not launched. However, we noticed that if we attach the debugger manually, it also launches a new instance.

**We suspect this is an issue on Apple's side**, so we have filled a bug report to them. However, so far we were only able to reproduce it with GLFW, therefore we'll share the same bug report here.

The following application is a minimum reproducible example, it uses GLFW 3.3.8. (Also reproducible with 3.4.) When it's launched it immediately opens a second application window when debugging is enabled in the scheme.

```
#include <GLFW/glfw3.h>

int main(int argc, char** argv) {


    if (!glfwInit()) {
        return 0;
    }
    
    GLFWwindow *glfwWindow = glfwCreateWindow(100, 100, "Test", nullptr, nullptr);
    glfwSetWindowPos(glfwWindow, 0, 0);

    while(true) {
        
    }
    
    return 0;
}
```

Attaching LLDB manually from terminal doesn't reproduce this issue. It only happens when Xcode is used to attach the debugger.

**Comment by kkaefer** [comment]
Here’s a minimal CMake file to reproduce this, with `main.cpp` being the contents of the example code on https://www.glfw.org/documentation.html

```
cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
project("example" LANGUAGES C CXX)

add_subdirectory(glfw)
add_executable(example main.cpp)
target_link_libraries(example PUBLIC glfw "-framework OpenGL")
```

**Comment by dougbinks** [comment]
> Right after the launch of the application, a secondary instance is launched which is an unexpected behaviour.

GLFW does not contain any code for launching applications, nor does it fork the process, so if this is a second instance (i.e. a second process) this can't be due to GLFW.

If this is a second window in the same process then I'm still fairly sure this isn't due to GLFW, but it could be an interaction with the debugger and window creation code. That does seem very unlikely though. I don't have a system which can run Xcode 16 so I can't test this myself.

One difference between the GDB debugger and XCode is that XCode uses Mach ports to track exceptions, but I can't see how that might cause GLFW to open two windows.

Could you confirm if this is a second process or a second window in the same process?

**Comment by endanke** [comment]
@dougbinks it's a second process. The way it's launched is through an external terminal window which launches the same application an additional time. Meanwhile the first instance is launched normally by Xcode. (I also see two separate processes in the activity monitor.)

**Comment by dougbinks** [comment]
Thanks for the quick response!

I also suspect it's an issue in Xcode, as I can't see how GLFW itself is involved since it doesn't launch processes.

In case you want to explore further, have you tried debugging any of the GLFW examples, and is there a difference between debugging examples like `boing.c` which is GUI only and the test `events.c` which has a console?

**Comment by Nelarius** [comment]
Hey there @dougbinks ,

I suspect this is an Xcode issue, because I observed the same problem in a project using SDL. This can be observed in the examples that ship with the repository:

```
$ git clone http://github.com/libsdl-org/SDL.git && cd SDL
$ cmake -B build-xcode -S . -G Xcode -DSDL_EXAMPLES=On
```

Running the `game-snake` and `renderer-lines` examples, I observed multiple windows opening up, just like @endanke with GLFW.

**Comment by dougbinks** [comment]
Thanks @Nelarius , that helps.

I'm wondering if this could also be an issue with CMake's XCode output when using the latest version of XCode.

**Comment by guy-stewart** [comment]
Hello @dougbinks , @endanke , here is another data point for you: I am using SDL2, and after months with no problems I started seeing the issue today only after using  instruments for the first time to search for a memory leak.  git diff did not show up any changes to the schema management plist.

**Comment by mcmara** [comment]
I had the same issue, on a MacMini M4 pro and Xcode 16. The secondary instance after launching the executable with Xcode consisted in the opening of one or two terminals. Tried to associate in Finder generic bash scripts to VSCode, and this time an empty instance of VSCode was opening (instead of a terminal). 
Also, this thing happened only with the SECOND launch after restarting Xcode. A lot of randomness!

Tried this minimal code:

```
#include <GLFW/glfw3.h>
#include <cstdio>
static void error_callback(int error, const char* description) {
    fprintf(stderr, "GLFW Error %d: %s\n", error, description);
}
int main() {
    freopen("/tmp/glfw-only.log", "w", stderr);
    fprintf(stderr, "Pre-glfwInit: OK\n");
    glfwSetErrorCallback(error_callback);
    glfwInit(); // Breakpoint
    fprintf(stderr, "Post-glfwInit: OK\n");
    // Disable input-related hints
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_FOCUSED, GLFW_FALSE); // Avoid input focus
    glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE); // Hide window
    GLFWwindow* window = glfwCreateWindow(800, 600, "GLFW Only", NULL, NULL); // Breakpoint
    fprintf(stderr, "Post-glfwCreateWindow: OK\n");
    glfwMakeContextCurrent(window); // Breakpoint
    fprintf(stderr, "Post-glfwMakeContextCurrent: OK\n");
    glfwShowWindow(window); // Show after creation
    while (!glfwWindowShouldClose(window)) {
        glfwSwapBuffers(window);
        glfwPollEvents();
    }
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```
and I was getting this:
```
$ cat /tmp/glfw-only.log 

OSLOG-5CF15220-804E-4865-8731-FA387250C58A 7 80 L 0 {t:1749911150.761122,tz:300,tzDST:1,tid:0x32aea4,type:"Error",subsystem:"com.apple.TextInputUI",category:"CursorUI",offset:0x97a8,imgUUID:"2900BB92-9421-342D-BD43-13A7AB8EB3FF",imgPath:"/System/Library/PrivateFrameworks/TextInputUIMacHelper.framework/Versions/A/TextInputUIMacHelper",procName:"greenworks",pid:10955,uid:501}	ViewBridge to RemoteViewService Terminated: Error Domain=com.apple.ViewBridge Code=18 "(null)" UserInfo={com.apple.ViewBridge.error.hint=this process disconnected remote view controller -- benign unless unexpected, com.apple.ViewBridge.error.description=NSViewBridgeErrorCanceled}
Pre-glfwInit: OK
Post-glfwInit: OK
Post-glfwCreateWindow: OK
Post-glfwMakeContextCurrent: OK
```
Solved by adding a 1-second delay before the `glfwInit();` call as you suggested above. Works for me, as a temporary workaround.
