### ISSUE TITLE
Explicit maximization support

### ISSUE THREAD

**Issue by retep998** [glfw/glfw#266]
A maximized window is treated differently from a normal window on many platforms (most notable being Windows).
Having an API to determine whether a window is maximized, and to change whether or not it is maximized would be very useful.

**Comment by andrewrk** [comment]
This is one of those issues that needs to be solved for GLFW to be a good choice for tool writers.

**Comment by elmindreda** [comment]
Moving this to 3.3 because I want to put out a release including Vulkan support as soon as possible.

The blocking issues for this feature are:
- [ ] Should it use zoom or Lion full screen on OS X?
- [ ] Is it possible to have a newly created window enter this state before being shown?
- [ ] Should un-maximization be done with `glfwRestoreWindow` or a new function?
- [ ] Should there be an event callback?

**Comment by shurcooL** [comment]
> Should it use zoom or Lion full screen on OS X?

I think they are 2 separate modes.

Zoom is most like the Windows maximize. Lion full screen is more like a way of switching to a borderless fullscreen window.

**Comment by elmindreda** [comment]
@shurcooL True, but Lion full screen is what currently happens when you click the analog of the maximization button for GLFW windows and many other OS X applications.

**Comment by shurcooL** [comment]
> but Lion full screen is what currently happens when you click the analog of the maximization button for GLFW windows and many other OS X applications.

Yeah. It's still possible to have the old zoom behavior by Option-Clicking (holding Option/Alt key, then Left Clicking with mouse). But normal click is now indeed mapped to fullscreen.

There's no ideal mapping to Windows.

**Comment by elmindreda** [comment]
All right, zoom it is then.

**Comment by elmindreda** [comment]
One item remaining. Unless someone objects I'll go with the results of [this poll](https://twitter.com/elmindreda/status/677125720410357760).
