### ISSUE TITLE
Desktop resolution full screen window disappears after deminiaturization

### ISSUE THREAD

**Issue by elmindreda** [glfw/glfw#407]
1. Run `iconify -f`
2. Press *Space*
3. Click the dock icon

**Comment by elmindreda** [comment]
No longer able to reproduce this on 10.10.5.

**Comment by shurcooL** [comment]
I tried the reproduce steps on OS X 10.11.1 (15B42). I tried it on `latest` and `master` branches.

I don't think I could see any issues. I'm not quite sure what the issue was, but it seemed behave as expected. Pressing space would minimize the fullscreen window, and clicking the dock icon would restore it. I could do it multiple times with consistent results.

**Comment by elmindreda** [comment]
@shurcooL That's what I'm seeing as well. Previously, restoring a full screen window from the dock would visibly animate the restoration but as soon as it reached full size it would disappear.

**Comment by shurcooL** [comment]
I see. Sounds like it's not an issue then. :)
