### ISSUE TITLE
Event processing blocks during window resizing

### ISSUE THREAD

**Issue by zhanggyb** [glfw/glfw#408]
Hello, I'm not sure this is a bug in GLFW, and this issue exists in GLFW 3.0.4 and the latest 3.1 master:

Does anyone notice that in OSX, the OpenGL Context is not rendered (partially or totally) when resizing the window, just as shown in the screenshots below:

![resize_window_bug1](https://cloud.githubusercontent.com/assets/1978235/5605861/b8658ae8-944e-11e4-8ac9-abdf3f136936.png)

![resize_window_bug2](https://cloud.githubusercontent.com/assets/1978235/5605871/0db38e82-944f-11e4-80f4-8ee859721d79.png)

There's no such issue in Linux build.

**Comment by slimsag** [comment]
I get the same behavior (no rendering during resize) on Windows as well.

**Comment by elmindreda** [comment]
See the window refresh callback.

**Comment by shurcooL** [comment]
> Does anyone notice that in OSX, the OpenGL Context is not rendered (partially or totally) when resizing the window, just as shown in the screenshots

Yes, that's the usual behavior. It happens when you have a typical simple `for { render; swap buffers; poll events; }` main loop. For example, you can see that behavior if you try the `Gears` app in `examples` folder.

I forgot about it, but as @elmindreda pointed out, the window refresh callback can be used to improve the behavior.

I just played with it, and my understanding of what happens (please correct if inaccurate) is this:

- When resizing the window on OS X, poll events blocks and does not return until user releases mouse button to stop resizing.
- In a typical for loop as shown above, that means rendering and swapping buffers stops to occur.
- However, you can (is this correct?) perform rendering and swap buffer, but not poll events (is this correct?) in the refresh callback, which is called while execution is inside poll events.

I've tested it out with a simple `gl.Clear(gl.COLOR_BUFFER_BIT)` and `window.SwapBuffers()` inside the refresh callback and it worked as expected to improve the resizing behavior.

**Comment by elmindreda** [comment]
Yes, it's perfectly fine to call `glfwSwapBuffers` from a callback, or from another thread if you are rendering there, and either method will fix this issue.

**Comment by zhanggyb** [comment]
OK, I understand now. Thanks!
