### ISSUE TITLE
Windowed full screen window minimizes when mouse click on another monitor

### ISSUE THREAD

**Issue by httpdigest** [glfw/glfw#447]
Hi,

I have written a simple app that uses the "windowed full screen" window, as described by the documentation: http://www.glfw.org/docs/latest/window.html#window_windowed_full_screen.

The window is correctly created and fills the whole monitor (which is the primary monitor obtained via glfwGetPrimaryMonitor(). I set the video mode parameters via the respective glfwWindowHint() function to those obtained via glfwGetVideoMode() of that monitor.

Now, when the window is displayed on the monitor (which is an external monitor attached via DisplayPort), and when I then mouse-left-click on a different monitor (laptop display), the GLFW window is minimized and also glfwGetFramebufferSize() reports then 0, 0.

I am on Windows 7 64-bit.
And I was using a custom CMake / Visual Studio 2015 amd64 static library Build of GLFW git branch "master" on the current revision 4188c2...

I think that even when mouse-clicking on the space of a different monitor, the GLFW window should stay intact on the other monitor.

- Kai

**Comment by elmindreda** [comment]
[GLFW_AUTO_ICONIFY](http://www.glfw.org/docs/latest/window.html#window_hints_wnd).

**Comment by bornskilled200** [comment]
If you set the window hint for GLFW_AUTO_ICONIFY before you create your window, it should fix your problem.
```c
glfwWindowHint(GLFW_AUTO_ICONFIY, GL_FALSE);
```
GLFW_AUTO_ICONIFY specifies whether the (full screen) window will automatically iconify and restore the previous video mode on input focus loss. This hint is ignored for windowed mode windows.

However I believe what you said is the expected behavior and might I suggest putting a note there in the documentation.

**Comment by tombsar** [comment]
The documentation for `GLFW_AUTO_ICONIFY` says this:

> This hint is ignored for windowed mode windows.

So is a "windowed full screen" window not counted as a "windowed mode" window?

**Comment by bornskilled200** [comment]
I read this that a "Windowed Fullscreen/Borderless Fullscreen" for glfw is a fullscreen mode that doesnt change the monitor's mode (resolution, refresh rate, etc.).

**Comment by httpdigest** [comment]
Thanks @bornskilled200 and @elmindreda for the info with auto iconify.
That did solve the issue.
However, once the window loses the focus because of me clicking on another monitor, the Windows Task Bar now gets visible over the GLFW window.
That might be expected behaviour (as it also happens with for example fullscreen YouTube videos on Chrome/HTML5), but is there a way to avoid this?

**Comment by bornskilled200** [comment]
I would do a borderless window. This is slightly different in coding
```c
// GLFW_FLOATING was not necessary for me in Windows 8.1 but might be for others
// The documentation also says that GLFW_FLOATING is primarily for debugging purposes
glfwWindowHint(GLFW_FLOATING, GL_TRUE);
glfwWindowHint(GLFW_DECORATED, GL_FALSE);
window = glfwCreateWindow(mode->width, mode->height, "Simple example", NULL, NULL);
```

Two notes for the behaviour you want
1) There is no way for you to stop the taskbar from showing without also forcing other applications to be hidden. This is because the taskbar is essentially "always-on-top." 
2) They would need to kill your application to access other programs. This could be incredibly bad especially for people who do not have multi monitor setups.

**Comment by shurcooL** [comment]
> `GLFW_FLOATING` specifies whether the window will be floating above other regular windows, also called topmost or always-on-top. This is intended primarily for debugging purposes and cannot be used to implement proper full screen windows. This hint is ignored for full screen windows.
