### ISSUE TITLE
glfwGetWindowAttrib - overloaded return value of zero: GL_FALSE is a valid zero, zero is an error

### ISSUE THREAD

**Issue by uglycoder** [glfw/glfw#485]
3.1.1

From docs
This function returns the value of an attribute of the specified window or its OpenGL or OpenGL ES context.
Returns:The value of the attribute, or zero if an error occurred.

GLFW_OPENGL_DEBUG_CONTEXT is GL_TRUE if the window's context is an OpenGL debug context, or GL_FALSE otherwise.

My comment:
GL_FALSE is zero, a valid non-error value. But zero is supposed to indicate an error.
Hence it is not possible to know if an error occurred.

**Comment by elmindreda** [comment]
Correct. There is no value *reserved* for errors. That might limit future hints. The documentation simply states what value is returned if an error does occur. However, this function should not fail as long as GLFW is initialized and the attribute are valid. Technically the window handle needs to be valid as well, but if it isn't your application will likely crash instead.

If you really *need* to know, you can tell an error occurred because the error callback will be called, but as a rule you will get a valid value from this function as long as you pass in valid arguments.

**Comment by uglycoder** [comment]
OK. So the docs need updating to reflect the function's behaviour.

Something like this to be added?
Pre-condition: valid window handle and attrib value for arguments. Library is successfully initialised.
Post condition: return value is valid value.
Error condition: Error callback will trigger if set.

**Comment by elmindreda** [comment]
Yes, that should likely be clarified. However, it's consistent across the API. Every function returns zero for all numeric values on error, whether by out argument or return value.

**Comment by elmindreda** [comment]
The documentation has been updated. Thank you for reporting this!
