### ISSUE TITLE
Use GLXWindow instead of Window

### ISSUE THREAD

**Issue by Kangz** [glfw/glfw#507]
While browsing your source code I found that you are using the X11 handle of the window for arguments that require a GLXDrawable (in glx_context.c, for MakeCurrent and Swapbuffers). While this is correct, it is only to preserve backwards compatibility (see GLX 1.4 spec section 2.1), you might want to update it to use a GLXWindow instead.

**Comment by elmindreda** [comment]
That's definitely something to do once GLFW starts requiring GLX 1.4 but it currently only requires 1.3.

**Comment by Kangz** [comment]
Min, I checked and this notice is already present in the GLX 1.3 spec; I quoted the GLX 1.4 one because it is the one I had open.

**Comment by elmindreda** [comment]
Hmm, so it does. I'll look into this when I rework colormap handling.

**Comment by elmindreda** [comment]
With 496f559c9af3c1c600d134f0ad06929628a7f50c in place, this can now be implemented.

**Comment by Kangz** [comment]
Nice, thank you!

**Comment by tobyp** [comment]
This change leads to some problems in conjunction with cairo, which uses `Window` to create surfaces in its GLX backend.

I create a cairo surface for a GLFW window using `cairo_glx_device_create(Display *, GLXcontext)` and `cairo_gl_surface_create_for_window(cairo_device_t*, Window, int, int)`, which fails with an X error in `X_GLXMakeContextCurrent` on the first call to `cairo_paint`. This does not happen before commit 962497b.

Does this change somehow disassociate the GLX surface from the X11 Window? Is cairo at fault for using `Window` instead of `GLXWindow` here?

I tested on Arch Linux, Intel(R) Ivybridge Mobile GPU, Mesa 11.2.2, OpenGL 3.0 using [this minimal test gist](https://gist.github.com/tobyp/53fbf1bdff40bbda8f2509a73821f07e)

**Comment by tobyp** [comment]
On Intel grarphics, the aforementioned X error occurs. Using nVidia graphics via Bumblebee (`nvidia` 367.27, not `nouveau`) does render, but with extreme flickering and incessant warnings: `primus: warning: glXSwapBuffers: no current context`.

I modified my code to use EGL; this works perfectly on Intel. NVidia does not seem to support EGL at all: `Error 65542: EGL: Failed to initialize EGL: EGL is not or could not be initialized`.
