### ISSUE TITLE
Z reported as GLFW_KEY_Y and vice versa

### ISSUE THREAD

**Issue by softwarefailure** [glfw/glfw#518]
I recently upgraded to GLFW 3.1.1 from 3.0 and noticed that pressing Z on a German keyboard is now reported as GLFW_KEY_Y and pressing Y is reported as GLFW_KEY_Z. In GLFW 3.0 this was working correctly, I just double-checked it again.

**Comment by elmindreda** [comment]
What OS are you on?

**Comment by softwarefailure** [comment]
Oops, should've mentioned that: Windows 7.

**Comment by elmindreda** [comment]
The key callback deals with physical keys and names them according to their values in the US keyboard layout. There was a bug (#114) in 3.0 that broke this behavior on Windows. This bug was fixed in 3.1.

If you want to input text, see the character callback.

For more information, see [keyboard input](http://www.glfw.org/docs/latest/input.html#input_keyboard) in the input guide.

**Comment by softwarefailure** [comment]
Alright, I didn't see that it is supposed to return the US keyboard layout because
of the bug in 3.0. This issue can be closed then.

**Comment by Extrawurst** [comment]
i have the exact same problem and i really don't understand it (still). how can i detect in a platform independent manner that the combination "CTRL+Z" was pressed ? 
OnKey reports them wrong on my german keylaout on win32 and OnChar won't report the event at all...

**Comment by elmindreda** [comment]
@Extrawurst #464

**Comment by Avanatiker** [comment]
This lib is the worst.
