### ISSUE TITLE
Specifying a monitor force entering fullscreen mode.

### ISSUE THREAD

**Issue by Groovounet** [glfw/glfw#526]
With the following code, GLFW creates a fullscreen window (changing the monitor resolution to 640 \* 480).
Simply replacing "Monitor" by "nullptr" in glfwCreateWindow, GLFW would create a windowed window.

I think there is a bug here. \o/

``` C++
void key_callback(GLFWwindow* Window, int Key, int Scancode, int Action, int Mods)
{
    if(Key == GLFW_KEY_ESCAPE && Action == GLFW_PRESS)
        glfwSetWindowShouldClose(Window, GL_TRUE);
}

void main_window(int argc, char* argv[], GLFWmonitor* Monitor)
{
    GLFWwindow* Window = glfwCreateWindow(640, 480, argv[0], Monitor, nullptr);
    glfwSetKeyCallback(Window, key_callback);
    glfwMakeContextCurrent(Window);

    while (true)
    {
        glfwPollEvents();

        if (glfwWindowShouldClose(Window))
            break;

        glClearColor(1.0f, 0.5f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        glfwSwapBuffers(Window);
    }

    glfwDestroyWindow(Window);
    Window = nullptr;
}

int main(int argc, char* argv[])
{
    glfwInit();

    int MonitorCount = 1;
    GLFWmonitor** Monitors = glfwGetMonitors(&MonitorCount);
    MonitorCount = 1;

    main_window(argc, argv, Monitors[0]);

    glfwTerminate();

    return 0;
}
```

**Comment by Groovounet** [comment]
By the way, what I am trying to do is creating a window per monitor, each running on separated threads. Am I supposed to call glfwCreateWindow in worker threads or the main thread?

**Comment by shurcooL** [comment]
> Simply replacing "Monitor" by "nullptr" in glfwCreateWindow, GLFW would create a windowed window.
>
> I think there is a bug here. \o/

It seems to be working as intended. Have you checked the docs on `glfwCreateWindow`?

http://www.glfw.org/docs/latest/group__window.html#ga5c336fddf2cbb5b92f65f10fb6043344

    [in]	monitor	The monitor to use for full screen mode, or NULL to use windowed mode.

**Comment by shurcooL** [comment]
> what I am really trying to do is creating a window per monitor

In that case, you'd want to specify `NULL` for `monitor` when calling `glfwCreateWindow`, and then use `glfwSetWindowPos` to position your windowed (non-fullscreen) windows. You'll want to query monitors for their virtual position, see http://www.glfw.org/docs/latest/monitor.html#monitor_pos.

**Comment by Groovounet** [comment]
[in]    monitor The monitor to use for full screen mode, or NULL to use windowed mode.

I didn't saw that behavior but that not a great behavior because it implies that the OpenGL context created for that window will be the one connected to main screen so glfwSetWindowPos isn't useful to me. 

On my setup, 3 screens, each screen is connected to a different GPU (AMD, Intel and NVIDIA) so the idea is to create a window per device.

Checking with the fullscreen mode, it looks like that GLFW doesn't support it either in that case. :/
I guess that's a feature request then.

I think ideally GLFW should support these cases:
- Always creating OpenGL contexts from the main monitor (Current)
- Creating OpenGL contexts using the device corrected to the requested monitor (Probably Windows only)
- Creating OpenGL contexts using the same device as the master context when context sharing is requested.

**Comment by elmindreda** [comment]
> Am I supposed to call glfwCreateWindow in worker threads or the main thread?

[All object creation and destruction must be done on on the main thread](http://www.glfw.org/docs/latest/intro.html#thread_safety).

> I didn't saw that behavior but that not a great behavior because it implies that the OpenGL context created for that window will be the one connected to main screen so glfwSetWindowPos isn't useful to me.

If the window position trick happens to work on your machine, it may work for full screen GLFW windows, as those are positioned on the desired monitor before context creation.

However, GLFW doesn't really support selection on heterogeneous multi-GPU desktop systems, mostly because I haven't been able to find a stable mechanism for doing so aside from the workstation-GPU-only extensions, partly because such systems seem to have been getting increasingly rare and also because I don't have one myself to experiment on.

I look periodically for any reliable method and did so again yesterday and today but turned up nothing of value. The most I've been able to find are horrible hacks for deciding which single ICD will be the one that a given process gets to talk to. Do you know of any usable method? I'd love to implement it.

**Comment by elmindreda** [comment]
I don't have the hardware or information necessary to get anywhere with this.
