### ISSUE TITLE
Steam Controller support

### ISSUE THREAD

**Issue by Sheado** [glfw/glfw#619]
Hi All, 

It would awesome if Steam Controller support was added into GLFW. If not that, then at least being able to detect it as a controller would be great. 

Thanks!

**Comment by elmindreda** [comment]
If there's a way to access it without the Steamworks SDK then it'll be added. For software headed to Steam, however, Valve's own API is infinitely superior to what GLFW could offer.

**Comment by Halsys** [comment]
I did some research on this, for you to get access to the SDK you need a Steamworks SDK account. 
Its not hard getting one, you just need to go this link; https://partner.steamgames.com; and sign in with your steam account and attempt to access the SDK. With that they have some examples and a VERY detailed header file for just the controller alone. Sadly, you need partial support with the entire SDK to use the controller because a function called "RunFrame" needs to be called, and a callback event called "SteamAPI_RunCallbacks" calls this for you. There is also a header and source that integrates on top of SDL that handles everything without the need to access the controller's header file directly. It would be easier to develop something like this with GLFW and have them include it as part of their SDK. Anyone feel like contacting VALVE to have GLFW be supported by their SDK?

**Comment by elmindreda** [comment]
To use the Steam controller properly, use Valve's API. It exposes all the things that are cool about the hardware that won't fit in the GLFW joystick API. Games written with GLFW will work with the XInput emulation once #232 is merged.
