### ISSUE TITLE
glfwSetFramebufferSize

### ISSUE THREAD

**Issue by xanather** [glfw/glfw#625]
There is no glfwSetFramebufferSize but there is support for glfwSetWindowSize and the somewhat related glfwSetFramebufferSizeCallback.

Is there a reason for this? My framework works with the size of back-buffers directly, not being able to directly set the frame buffer size is an issue for me.

**Comment by elmindreda** [comment]
The reason is that it's a tricky thing to do in a predictable way.

On OS X the ratio between window size and framebuffer size depends on which monitor the system considers your window to "be on". Resizing the window may shift the midpoint to another monitor and thus change the ratio. If we are talking about full screen, well, resolutions are listed in points, not pixels. The system also lists resolutions where pixels and points map 1:1 but doesn't provide any method to find out in advance which these are.

On Windows 8.1 and later the window and framebuffer sizes are 1:1 but the per-monitor DPI system suggests new window sizes also based on what monitor the window is considered to "be on".

X11 is the only system I know where this would be a sane operation, but 1/5 doesn't make for a good GLFW function.

**Comment by xanather** [comment]
Okay, thanks for that info. I guess I will just attempt to set the resolution with glfwSetWindowSize and notify the user if they got a resolution they didn't select for now.

Maybe something will pop up in the future? Anyway I'll leave this issue open but feel free to close it.

**Comment by elmindreda** [comment]
Is this specifically about full screen or do you need a general solution?

**Comment by xanather** [comment]
General solution. Its both for inside and outside full-screen. I allow users to set their resolution from within a settings panel from within the program.

**Comment by xanather** [comment]
I really need an OS to properly test this on where screen coordinates != pixel coordinates, is there an option to somehow enable it on Ubuntu? I don't have any retina displays.

**Comment by elmindreda** [comment]
No, you need OS X for that.

**Comment by elmindreda** [comment]
I'm closing this but I'm aware of the problem and will keep a look out for a more user-friendly solution.
