### ISSUE TITLE
Char callback and release event

### ISSUE THREAD

**Issue by hodiizidor** [glfw/glfw#668]
Is there any particular reason that there isn't key release event available under GLFWcharfun?

It's really hard to me to distinguish when for example simple question mark is released. On my english keyboard '?' is  Shift+/, on other layout is Shift+,. While getting lowercase of normal alpha keys is simply determined with keypress callback and determining if shift is pressed, all characters that are invoked with pressing shift, alt and some key if almost impossible to determine if key is released.

Or is there any workaround for this kind of problem?

**Comment by tombsar** [comment]
The character callback is intended for receiving textual input, as there isn't always a direct relationship between keys and characters (e.g. for languages that use don't use the English alphabet). See https://en.wikipedia.org/wiki/Input_method.

If you care about particular key press/release events, then you want the key callback. In this case your problem will be identifying which glfw keycode maps to a particular key in a particular keyboard layout. Maybe `glfwGetKeyName` is of use?

**Comment by hodiizidor** [comment]
As I see it should help, but it doesn't. Key callback returns same key and scancode if I press either 'A' or 'a', so the result from glfwGetKeyName is always A. Same for / and ?, result is always /.

**Comment by tombsar** [comment]
> Key callback returns same key and scancode if I press either 'A' or 'a'

Surely this is desired behaviour, since they are actually the same key? The `mods` parameter should tell you if Shift was held when the key was pressed.

Unfortunately I don't know of a keyboard-layout agnostic way of detecting "the key with '?' on it was released". Can someone else weigh in?

**Comment by hodiizidor** [comment]
> Surely this is desired behaviour, since they are actually the same key? The mods parameter should tell you if Shift was held when the key was pressed.

yea I saw that scancode is only used in key callback if GLFW_KEY_UNKNOWN is got in key parameter. 

I would like to go back to my first question. 

I understand that key callback is useful in its own way. You can get several keys pressed, you can ignore caps, you can get shift, ctrl, alt and all other keys pressed/released.

I don't understand why there isn't released/repeat event fired in char callback function. It is useful also. With key function I'm not sure that even lowercaps a is pressed if you press A. I just presume that SHIFT+A is uppercaps A. With key callback I can tell if shift is pressed/released and if 'a' is pressed/released. With char callback I should have only get 'A' char. But also there should be release event.

It's a bit crazy that I need to hack, just to get if any char is released. It's basic behavior that should be available and easily implementable.

**Comment by shurcooL** [comment]
From http://www.glfw.org/docs/latest/input.html#input_key:

> GLFW supports text input in the form of a stream of Unicode code points, as produced by the operating system text input system. Unlike key input, text input obeys keyboard layouts and modifier keys and supports composing characters using dead keys.

The keywords are that text input is a *stream* of characters. It's one character, followed by another, followed by another.

There is no explicit relationship to keys, presses, or releases, it's just a series of characters. They can be produced by a keyboard, a joystick, or a microphone with a voice-to-text system; that's up to the operating system.

If you're building a user-level application and you want to support text entry, you should use text input API of GLFW to get characters, and key presses/releases do not apply. If you want physical keyboard button presses/releases, use key input, which has no notion of keyboard layout.

If you're building a low-level systems application and you want to do something custom, then it's likely you'd want to use the key input and build your own text abstraction engine on top of that.

GLFW's API is optimized for user-level applications that follow UI principles of the underlying OS, which is why it exposes the information as described above.

Does that help answer your question?

**Comment by elmindreda** [comment]
@tombsar and @shurcooL explained the issue very well. Closing this.
