### ISSUE TITLE
Can not create window when running through renderdoc in latest git

### ISSUE THREAD

**Issue by haikarainen** [glfw/glfw#720]
I tend to use renderdoc under windows for OpenGL-debugging, and ever since I compiled GLFW from the latest git I haven't been able to debug my applications with renderdoc. Switching GLFW back to 0.9.7.1 (NuGet in Visual Studio) fixes this issue.

This might not be GLFW's fault, but I still think it would be very useful to track this issue down. Renderdoc is the best (if not the only good) GPU debugger out there for windows, that works with both AMD and NVidia, I think it's important to preserve compatibility with it.

EDIT: Missed crucial info: The problem I get is glfwCreateWindow fails, complaining about "Win32 failed to create window"

**Comment by baldurk** [comment]
Not trying to step on any toes, but I tried reproducing this (since it sounds like it's likely a renderdoc bug), but running with the 'heightmap' sample from master it works OK for me.

**Comment by haikarainen** [comment]
@baldurk Hmm same results for me, heightmap examples work through renderdoc. I will try to create a minimal reproducable example!

**Comment by Sciolyte** [comment]
I've had a similar issue in my projects, but I'm not sure if it's related. In my case it was because I called 'glfwInit' in an entry point within a dll, which my main project was linked to. This works just fine when running the program regularly, but when running it via RenderDoc, the problem the OP posted occurs.
If I don't use the dll entry point to initialize GLFW, RenderDoc can run it without a problem.
I've attached a minimal example to this post, but as I said, I'm not sure it's actually related.
[test_glfw.zip](https://github.com/glfw/glfw/files/192059/test_glfw.zip)

**Comment by elmindreda** [comment]
@Sciolyte Do not call those functions from DllMain. There are [severe restrictions](https://msdn.microsoft.com/en-us/library/windows/desktop/dn633971(v=vs.85).aspx#general_best_practices) on what you are allowed to do from DllMain and GLFW does many of them at init.

**Comment by haikarainen** [comment]
Sorry for just bailing on this issue, I never got to writing a minimal reproducable example, but I did have some amazingly stupid code for initializing GLFW (basically a singleton-class, that I instanced statically out of laziness). Changing this to a more expected behaviour (non-static singleton instance for every class instance that needed it) fixed the issue for me

**Comment by elmindreda** [comment]
@haikarainen Thank you for the follow-up!
