### ISSUE TITLE
glfwSetKeyCallback triggers multiple key events after holding a key down

### ISSUE THREAD

**Issue by larsjarlvik** [glfw/glfw#747]
I just implemented camera movements and noticed that the camera moved forward for a bit after releasing W. After some investigation I noticed that glfwSetKeyCallback triggered another shorter sequence of GLFW_PRESS, GLFW_REPEAT and GLFW_RELEASE after I've release the key. The longer I hold the key the longer the second sequence is.

To make sure it wasn't something in my code I downloaded the getting started example and added a simple `printf("%i  ", action);`

The output looked like this:

`1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 1 2 2 2 2 0`

Where the first 0 is when I actually released the key and the rest of the sequence are phantom key events.

I'm running GLFW 3.1.2 using the offical package on ArchLinux x64

**Comment by shurcooL** [comment]
> I just implemented camera movements and noticed that the camera moved forward for a bit after releasing W. After some investigation I noticed that glfwSetKeyCallback

This may be not directly related to the issue, but key callback is designed for text entry, so holding down a key will produce GLFW_REPEAT events. If you want to achieve frame-rate-independent camera movement, you'd likely want to use button callback and perform time-adjusted movements based on whether the buttons are pressed or released.

The extra `1 2 2 2 2 0` phantom key events may be a legitimate issue with the key callback, however (at a glance, I haven't tried to reproduce).

**Comment by Lazze2k5** [comment]
As I understand from http://www.glfw.org/docs/latest/input.htm glfwSetKeyCallback is for keyboard input while glfwSetCharCallback is for text input with encoding etc. I can't find a button button callback in the docs for keyboard, just mouse.

I've implemented it in the way that I have a bool array which I set the current key to true on GLFW_PRESS and false on GLFW_RELEASE. The problem is that due to the issue I'm experiencing it's set to true twice, first correctly and after that another shorter time after I've released the key which makes the camera move a bit further than it should.

Also the longer I hold the key the longer the false keydown will be. It also seems a bit FPS dependent as it's lot less shorter if I turn off vsync.

**Comment by shurcooL** [comment]
Apologies, what I said was completely incorrect because I confused "key" and "char" callbacks. I thought it was "button" and "key".

**Comment by elmindreda** [comment]
Can you reproduce this with the `events` test? If so, please post the output.

**Comment by Lazze2k5** [comment]
@elmindreda sorry what's the events test? I'm new to GLFW and quite rusty at C++, was a while ago so I need some more explanation.

**Comment by Spartan322** [comment]
[Events Test](https://github.com/glfw/glfw/blob/master/tests/events.c)

Also, don't you mean C?

**Comment by Lazze2k5** [comment]
Hehe, I do, got it mixed up in my head as I'm doing a bit of both at the moment.

However I've ran the events test and I couldn't reproduce the error. I investigated a bit further and found out that it only occurs when I have glfwSwapBuffers in my game loop.

Here's the output when I run it without changing any code, everything seems fine here:
http://pastebin.com/raw/7XXMgvee

And here's the output when I add glfwSwapBuffers to my code:
http://pastebin.com/raw/bW4GMZmK

Both times I just pressed W once for 3 seconds.

**Comment by nitya-dev** [comment]
Engo has the same unexpected output results as the test mentioned here. I could not see the bug in GLFW so did some extra testing. These are the results: https://gist.github.com/nitya-dev/094c12771e37fff8c06d8f6a02cd2cbf

Seems like this is upstream in the xorg server ?

**Comment by rdbv** [comment]
I have the same problem with glfwSetKeyCallback function.
Used GLFW version: 3.1.2 under Ubuntu 16.04, but problem exists on Debian too.
Code with bug: http://pastebin.com/PBTjhN6y
Example bugged output (W was pressed ~3 secs): http://pastebin.com/jEqYAqwi

**Comment by elmindreda** [comment]
I cannot reproduce this.

**Comment by acazuc** [comment]
Hi,

I have the same problem but i can't reproduce it with events test.
Events dump: http://pastebin.com/LwwWnyjM
You can see at the bottom that the key is up (i released it) but it go down again for some events.
It seems that the most I pressed the key, the most the bug will send fake key press events:
Short press time: http://pastebin.com/y2f1bptZ
Long press time: http://pastebin.com/G2eEQSds
I'm using GLFW 3.2.1 on Ubuntu 16.04 (3.2.1 X11 GLX EGL clock_gettime /dev/js Xf86vm)

Thanks

**Comment by acazuc** [comment]
Hi,

I investigated a little, and searched for alternative X events processing.
I tried to use XCheckMaskEvent instead of XPending to iterate over events. The good thing is that with that function, key presses never duplicate / bug. But sadly, using this function makes char events never happend.
I found that char events wasn't triggered because of ```if (!filtered)``` in [x11_window.c:1008](https://github.com/glfw/glfw/blob/master/src/x11_window.c#L1008). Disabling this test fix the char events.
Another event isn't triggered by using XCheckMaskEvent: the window destroy event.

I never touched X window before, so maybe it's not the good way to process events, but it seems to work well.

Thanks

**Comment by ThomsV** [comment]
I can reproduce it and it only happens if the rate at which `glfwPollEvents()` is called is low. In my case if it's less than ~50 refreshes per second. So the following will give phantom key-presses:

`while (running)`
`{`
 `    glfwPollEvents();`
  `    std::this_thread::sleep_for(std::chrono::milliseconds(30));`
`}`

**Comment by jrkoenig** [comment]
Calling glfwPollEvents() at 2fps (aka add a 500ms sleep to the main loop) seems to trigger it reliably on X.Org X Server 1.18.4, running on Ubuntu 16.10 with GLFW 3.2.0.

The solution is literally starring us in the face.

```
            if (window->x11.ic)
            {
                // HACK: Ignore duplicate key press events generated by ibus
                //       Corresponding release events are filtered out by the
                //       GLFW key repeat logic
                if (window->x11.last.keycode != keycode ||
                    window->x11.last.time != event->xkey.time)
                {
                    if (keycode)
                        _glfwInputKey(window, key, keycode, GLFW_PRESS, mods);
                }
            ...
```

Sure enough, if you disable `window->x11.ic` by disabling `im` globally (`if (XSupportsLocale())` -> `if (XSupportsLocale() && 0)` in `x11_init.c`), then there are **no phantom keypresses**. You can also see that each phantom keypress has an old timestamp exactly identical to that of a keypress that was already received and processed, validating that HACK comment.

My guess is ibus doesn't send the keypress until the previous event is actually removed from the queue/forwarded/whatever, so it takes N processing loops to clear N keypress repeats. When FPS > key repeat rate, there is no issue, but otherwise they pile up and it takes many event loops to clear the backlog.

The solution is rather simple. Rather than filtering based on the last received timestamp, instead discard any events *older* by more than say 10ms than the most recent key event received, to account for noisy timestamps. The current code assumes the duplicate keypresses are adjacent in the event stream, which is false at low FPS. I'll make a PR soonish.

**Comment by elmindreda** [comment]
@jrkoenig Thank you! I've added this to 3.3, but I have other issues to close before this one.

**Comment by ZenToad** [comment]
I not sure it matters at this point, but I can confirm that this is a bug on Ubuntu 16.04 and the fix did work for me.

**Comment by elmindreda** [comment]
This should be fixed now with 4ff66a7818e3eaa5362c828a18220b12f1cd9bc8.

**Comment by dulsi** [comment]
Any time frame on 3.3? Alternatively could a 3.2.2 release be made? Right now glfw is not that useful on Fedora Linux due to the phantom key presses.

**Comment by VjiaoBlack** [comment]
Hmm, I was having some similar bugs on a project I've been writing, and I've made sure to get GLFW 3.3; however, I still come across something really similar this issue? (PopOS)

Basically, when I hold down, say, "w" to move my camera "up" (I coded this), it'll move up - but when I release the "w", it'll stop and stutter, as if I had tapped it again afterwards.

I verified this with print statements I put in my key callback function, so I know the callback is somehow being called extra times.

Interestingly enough, if I hold the key down for a few seconds, I'll get:
PRESS       // good
RELEASE  // good
PRESS      // extra
RELEASE // extra

but if I only tap the key, I'll get
PRESS      // good
RELEASE  // good
RELEASE  // extra

In both cases, glfwGetTime shows that the extra events happen soon after the normal ones.

Some logs with timings:
INF: PRESS 2.965
INF: RELEASE 3.015
INF: RELEASE 3.049
vs
INF: PRESS 9.438
INF: RELEASE 11.596
INF: PRESS 11.630
INF: RELEASE 12.001

It seems to happen whether or not I have "glfwSwapBuffers" in my game loop.

Oh, and I already tried moving from 30 to 60 FPS (these numbers are from 60 FPS). It seemed to reduce the duration of this extra "window drifting" caused by the duplicate pair of key events, but I still get the duplicate keyevents!

Also, I tried the events test and checked the logs; things seem to be working right there?

Not sure what to do from here, so I thought I'd drop a msg, especially since what I'm experiencing is so similar to the original post?

**Comment by VjiaoBlack** [comment]
Hopefully helpful post-note:

I saw the "When FPS > key repeat rate, there is no issue, but otherwise they pile up..." line, so I decided to try it out. 
I did "xset r rate 190 100" to make my character repeat speed (not key repeat speed I think; specifically character repeat speed?) super fast - sure enough, the issue was worse. When I did "xset r rate 190 10" to make it super slow, I only saw the "press release release" pattern in my program, not the "press release press release" pattern.
