### ISSUE TITLE
Missing buttons xbox controller.

### ISSUE THREAD

**Issue by rgkirch** [glfw/glfw#794]
3.2.0 X11 GLX EGL clock_gettime /dev/js Xf86vm shared

I have a wired xbox controller. `glfwGetJoystickAxes' reports 8 axes. I'm missing the bumpers, back and start, the thumbstick buttons, the large X button, and abxy.
Is this not supported? I haven't found any information on this.

OS: Antergos  Minimal-ISO-Rolling
Kernel: x86_64 Linux 4.6.2-1-ARCH

**Comment by elmindreda** [comment]
Was this closed by accident?

**Comment by rgkirch** [comment]
Not closed on accident. The accident was not noticing `glfwGetJoystickButtons.` Many thanks. I've got no problems.

**Comment by rgkirch** [comment]
You added this to the whaaat milestone?

**Comment by elmindreda** [comment]
The no-milestone milestone.

**Comment by rgkirch** [comment]
That's handy. How do you add labels? I didn't want this question to come across as a bug.

**Comment by elmindreda** [comment]
Only repository members can add labels.

**Comment by rgkirch** [comment]
Ok. Thanks.

**Comment by shurcooL** [comment]
I am curious about the no-milestone milestone, can you explain what it means, if it's meant to be public information?

> elmindreda added this to the 無 milestone 14 hours ago

I've initially started thinking of it as a milestone used to mark things that are not real bugs, and I interpreted the symbol to look like a rug... So I read the above phrase as "elmindreda swept this under the 無 14 hours ago".

Later, I searched/translated that symbol and learned it means "void", so that made me realize it looking like a rug may not be the intended purpose. Still, I don't quite know what the purpose and rationale behind it is, and I'd be curious to learn, if you can share this information.

**Comment by elmindreda** [comment]
@shurcooL That's it exactly!
