### ISSUE TITLE
glfwGetWindowPos and glfwSetWindowPos do not ignore decorations

### ISSUE THREAD

**Issue by Draghi** [glfw/glfw#800]
It appears that the either the window position callback or the glfwGetWindowPos/glfwSetWindowPos are not using the correct/same reference point. As the values provided by the callback and the glfwGetWindowPos are consistantly out by the size of my window decorations.

I confirmed this by performing a test where I create a window and set the position callback.
In the position callback I store the values that are passed in and then setting the window's position to them in the main update loop.
This results in the window jumping, normally when I drag the window.
However, if in the callback I store the values provided by glfwGetWindowPos then the window remains static and correctly moves when I drag the window.

In my case the values were different by -4 x and -18 y relative to the callback's values.

This suggests that the callback is providing client-area positions and glfwGetWindowPos/glfwSetWindowPos are operating on window cordinates. This is further suggested by setting the window position so that x = 0, this results in the window decoration's edge touching the side rather than the client area. Setting the position to x = -4 causes the client area's edge to line up with the edge of the screen instead. Lastly looking at the documentation for the XMoveWindow function, it says that x and y "define the new location of the top-left pixel of the window's border or the window itself if it has no border." and (atleast in the __glfwPlatformSetWindowPos function) the coordinates aren't translated from the client-area to include the window decorations.

It appears that the callback provides client-area positions while glfwGetWindowPos/glfwSetWindowPos are operating on the window+decoration positio
ns. This is further suggested by setting the window's x position to 0 which results in the border of the window being flush with the edge of the screen, in this case the callback provides the value 4 for x indiciating that the client-area's x isn't at the edge of the screen, while glfwGetWindowPos reports that x is at 0. Forcing the window's x position to -4 results in the client area being flush with the screen's edge, the callback reporting 0 and the glfwGetWindowPos reporting -4. 

The documentation for XMoveWindow also states that x and y "define the new location of the top-left pixel of the window's border or the window itself if it has no border" so I attempted changing the __glfwPlatformSetWindowPos function in x11_window.c like so:
```
XWindowAttributes xwa;
XGetWindowAttributes(_glfw.x11.display, window->x11.handle, &xwa);

XMoveWindow(_glfw.x11.display, window->x11.handle, xpos - xwa.x, ypos - xwa.y);
XFlush(_glfw.x11.display);
```
This causes the window position provided by the callback to work correctly, but in turn causes the values provided by glfwGetWindowPos to make the window jump around as one would expect. A similar modification should work for the get function as well, I believe. It also fixes setting the window's x-coordinate to 0 so that the client area is flush with the edge of the screen. I'm not 100% certain that the modification I made is technically correct, as I'm unaware how X11 operates.

I also don't currently have another linux distribution set-up or an alternative window manager set-up currently so I'm not sure where the problem acutally lies. 

I'm running Arch Linux 4.6.2-1 x86_64 with Xfce 4.12 + xfwm 4.12.3
I've observed this behavour with the current master branch (commit: 49f429018e5ef50db730439132a443c0bb1967e7)

If you need any more information, a test program or maybe a video just ask and I'll get right on it. 

PS: Sorry if it's a bit rambly / filled with spelling errors. It's pretty late at night right now and I wanted to get this all down and post the bug report before I forgot.

**Comment by Draghi** [comment]
I've attempt a fix in my fork at draghi/glfw@cb578984896b9a88e97e272fb899e40c1e87416d

Changes in x11_window.c:
In the ConfigureNotify event handling I changed it so that the event position is ignored and the values given by _glfwPlatformGetWindowPos are used instead [1224 -1237]
_glfwPlatformGetWindowPos offsets the top-left of the window to the client area [1696 - 1704]
_glfwPlatformSetWindowPos offsets the client area to the top-left of the window [1735 - 1740]

This results in the expected behavour on my system. The position callback and glfwGetWindowPos provide the same values. Forcing the window to 0,0 results in the client-area being flush with the sides of the screen. The same is true when window decorations are disabled for the window.

However, the solution is untested with any other window managers or with any other linux distributions. 

It's also probbably not exactly ideal, the change to the ConfigureNotify event handling isn't strickly needed in this case and very likely changes the values passed to the callbacks (multiple move events passing the same position), however I was unsure how to garentee that the event would consistantly provide the client-area position based on the documentation (my lack of x11/xlib/glfw-internals knowledge showing there).

**Comment by CaffeineViking** [comment]
Verified, I can reproduce @Draghi's issue #800 X11 bug. I have tested this on both DWM 6.1-3 and also on XUbuntu 16.04 LTS running XFCE 4.12 (with XFWM 4.12). I don't exactly know what values should be correct, but `GetWindowPos` returns the screen position of the client area, while a `SetWindowPosCallback` returns (x, y)-values of the actual window (client area + decorations). Below follows some observations.

Example: DWM 6.1-3 has only a one pixel border decoration, `GetWindowPos` gives me (1, 1) whenever I call `SetWindowPos` with (0, 0), while `SetWindowPosCallback` give me the values (0, 0). According to the documentation, `GetWindowPos` and `SetWindowPosCallback` should be returning the _screen coordinates_ (the X11 root) of the _client area_ (the framebuffer) implying (1, 1)? Meaning (if everything I have said and measured is correct), that both `SetWindowPos` and `SetWindowPosCallback` aren't correctly setting, and getting the position (not accounting for the window decorations), doing everything relative to a _window_.

If you would like to try this yourselves to indeed confirm this, I have made a small test program that will print the values of both `GetWindowPos` and `SetWindowPosCallback` whenever a window position event has happened. Hopefully (if this bug indeed exists), the values in each line should't match, whenever a displacement happens. Also, pressing 'T' will call `SetWindowPos`, try to assert that both `GetWindowPos` and `SetWindowPosCallback` return the same (x, y)-value, which should fail right now if there is a bug. The testing program: https://gist.github.com/CaffeineViking/8a8d1c77938070b86f3c5293d1a2cbba

Finally, the patch provided by @Draghi [Draghi/glfw](https://github.com/Draghi/glfw) seems to fix the position inconsistency between `GetWindowPos` and `SetWindowPosCallback`, which now return the same value in my testing program. However, something fishy happens when attempting to call `SetWindowPos` and then querying either `GetWindowPos` or `SetWindowPosCallback`, at least for me. Both of these return positions which are double what they should really be. I don't why, but this happens on my setup. I'll investigate further.

Anway, good work finding this bug @Draghi! Let's see if we can both figure out what's wrong here.

**Comment by Draghi** [comment]
That's very interesting. Under XFCE, atleast on my system, SetWindowPosCallback provides client area values and GetWindowPos + SetWindowPos return the actual position of the window + decorations. I'll need to double check that though as I might be mistaken, might not be able to verify for a day or two depending if I get some time to jump on a laptop.

**Comment by CaffeineViking** [comment]
Alright, good thing to note: it seems that similar things have been reported here before, in particular, the issues #274, #517 and #626 all sound very similar. I think it would be best to wait @elmindreda's verdict on this, if this has happened before, chances are changes to this will break behaviour for the other people too (leading to an endless loop of issues coming back, fixing back and forth for WMs).

**Comment by toxicwolf** [comment]
On KDE (kwin 5.6.5-3 (plasma)) `XGetWindowAttributes` returns an x and y of 0. So while @Draghi's patch fixes the consistency issues, on KDE it does not make `GetWindowPos` and `SetWindowPos` adhere to the documented behaviour - it operates on the window position (with decorations) instead of the client area position.

**Comment by elmindreda** [comment]
See if the `x11-windowpos` branch fixes this for you.

**Comment by CaffeineViking** [comment]
Verified @elmindreda's branch on various different systems. Below follow some short summaries of the observations I've made *before* and *after* applying the fix at the `x11-windowpos` branch. Might try more..

* **XUbuntu 16.04 + XFCE 4.12 + XFWM 4.12:** before `x11-windowpos` both *polled* and *callback* values didn't match up. *Polled* returned *window-relative* positions, while *callbacks* did return a *client-relative*. After applying `x11-windowpos` both *polled* and *callback* values return *client-relative* positions. **Nice!!**
* **Fedora 24 Workstation + GNOME 3.20 + Mutter 3.20:** before `x11-windowpos` *polled* values return some *mystery-relative* position, idk, while *callbacks* returned the correct *client-relative* positions. So, after applying `x11-windowpos`, *polled* and *callback* report the correct *client-relative* positions. **Nice!!**
* **Linux Mint 18 + Cinnamon 3.0 + Muffin 3.0.5:** before applying `x11-windowpos`, the *polled* values returned *window-relative* (i.e. with decorations) positions and *callbacks* returned *client-relative* area. After applying `x11-windowpos`, both *polled* and *callbacks* return the *client-relative* positions. **Nice!!!**

**Comment by elmindreda** [comment]
@CaffeineViking Thank you! From my own observations the fix appears to work on __Metacity__, __Fluxbox__ and __Blackbox__ as well, and I can confirm __Xfwm4__, which is my current main WM.
