### ISSUE TITLE
Compilation failure using older MSVC version

### ISSUE THREAD

**Issue by ngoldbaum** [glfw/glfw#821]
This came up in the context of cyglfw3, which is a python wrapper for GLFW3 written in cython. See https://github.com/adamlwgriffiths/cyglfw3/issues/22.

Python2.7 uses a relatively old version of MSVC that does not include stdint.h. This means that any program (or in this case a CPython C extension) that includes glfw3.h won't compile with this version of MSVC because no stdint.h is available out of the box.

I was able to work around this by adding a version of stdint.h to the includes directory of the GLFW binary distribution. To restore compatibility with this older version of MSVC, GLFW either needs to include a windows-specific version of stdint.h that only gets included on older versions of MSVC or drop the stdint.h import entirely.

**Comment by ngoldbaum** [comment]
Ah, I see that this is discussed in the commit message for https://github.com/glfw/glfw/commit/5661d03be875d28ee72e44a037b653250de24a53. So I guess this isn't really supported since you don't do testing for such old versions of MSVC. I'll leave this open in case a maintainer is ok with adding a VS2008-specific hack.

**Comment by elmindreda** [comment]
The problem is it's tricky to maintain support for a compiler I cannot get hold of. This may be the only thing preventing it from building now, but without continuous testing it's nearly impossible to know when new issues will arise. I only got back VS 2010 and 2012 after reinstalling thanks to detective work by @dougbinks, as MS has done their best to hide those versions as well.

I'll fix this if you or someone else will test before every release and submit the necessary fixes but I won't add complexity that will just rot and I won't keep it if that person disappears with no successor.

**Comment by ngoldbaum** [comment]
As far as obtaining the compiler, you can get a version of VS 2008 specifically for python2.7 from microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=44266

An automated test might be to simply try compiling cyglfw3 (or any Python C extension that imports glfw3.h) on python2.7.

**Comment by adamlwgriffiths** [comment]
There's an ISO I found on google for Visual Studio 2008 Express (DuckDuckGo didn't find anything)
https://go.microsoft.com/fwlink/?LinkId=104679

Incase you don't want to click random links - search terms were: visual studio 2008 express download
first hit.

**Comment by elmindreda** [comment]
MS fixed their site and now once again provides sane access to VS 2008.

**Comment by ngoldbaum** [comment]
Thank you for fixing this!

**Comment by elmindreda** [comment]
This isn't official support but I'll try to fix reported issues until the move to C99.
