### ISSUE TITLE
Init hints for ICCCM WM_CLASS components

### ISSUE THREAD

**Issue by kovidgoyal** [glfw/glfw#893]
I'd like a small enhancement to the hack for setting WM_CLASS. Currently both parts of the WM_CLASS are set to the initial title. Instead, could the title be split on the 30 character (ASCII record separator) so that the name and class parts of WM_CLASS can be set separately? Thanks.

**Comment by elmindreda** [comment]
Thanks! Will look into it.

**Comment by elmindreda** [comment]
This would be better served via platform specific hints than introducing magic into window titles.

**Comment by kovidgoyal** [comment]
Sure, if you are willing to do the work to setup the infrastucture for that, great. That would help with other things as well, such as support for the different types of clipboards in X11.

However, my suggested modification is much less work. Which approach you choose is entirely up to you, since you are the one who will be maintaing this codebase.

**Comment by elmindreda** [comment]
Which convention are you planning to use for WM_CLASS?

**Comment by kovidgoyal** [comment]
Not sure what you are asking? I am fine with any approach that allows me to set both parts of WM_CLASS independently. Either use a record separator in the title hack or setup some api for adding platform specifi properties to windows.

**Comment by elmindreda** [comment]
I'll be adding the `glfwInitHint` function similar to the current `glfwWindowHint` for (mostly platform specific) options that must be known at initialization to move them from compile-time to run-time and cut down on the need for people to (re-)compile their own binaries. Since WM_CLASS is used to expose application-global information, it seems to be a good fit for that mechanism.

I propose adding two X11 specific hints, one for each component of the property. These strings would then be used for all top-level X11 windows created by GLFW. Would this be sufficient for your needs?

**Comment by kovidgoyal** [comment]
Yes, that is fine, thank you :)
