### ISSUE TITLE
glfwSetTimer

### ISSUE THREAD

**Issue by 0xc0de** [glfw/glfw#925]
It would be great to have something like this:

```
GLFWAPI int glfwSetTimer( GLFWwindow * handle, unsigned int milliseconds ); // return timer_id
GLFWAPI void glfwKillTimer( GLFWwindow * handle, int timer_id );

typedef void (* GLFWtimerfun)( GLFWwindow * handle, int timer_id );

GLFWAPI GLFWtimerfun glfwSetTimerCallback( GLFWwindow* handle, GLFWtimerfun cbfun );
```

**Comment by shurcooL** [comment]
Is this possible to do with external APIs? I ask because it's better to keep scope of GLFW smaller when possible, so that it can do a better job at its [core responsibilities](https://github.com/glfw/glfw/issues).

For example, in Go, such basic functionality is [a part](https://godoc.org/time#Tick) of the standard `time` package. What about other environments?

That said, GLFW does take on [some time-related responsibilities](http://www.glfw.org/faq.html#what-timer-apis-does-glfw-use) already, so this might be a reasonable extension of that. I don't know if the plan/desire for next major version (GLFW 4) to keep that or drop it though (I don't see anything about [dropping it](https://github.com/glfw/glfw/wiki/GLFW-4.0-sketchbook)).

**Comment by elmindreda** [comment]
@0xc0de On which thread would the timer callback be called? If on the main thread, there is `glfwWaitEventsTimeout` to help with this. If on a secondary thread, you can use the C, C++ or OS threading functions.

**Comment by 0xc0de** [comment]
@elmindreda The timer callback would be called on the main thread. glfwWaitEventsTimeout is a good approach, but there is a problem to simulate several timers.

**Comment by elmindreda** [comment]
Just set the wait events timeout to the minimum of all the timers' timeouts.
