### ISSUE TITLE
mac port cmake find_package(glfw3 REQUIRED) does not init INCLUDE_DIR or LIBRARY_DIR variables

### ISSUE THREAD

**Issue by gentili** [glfw/glfw#929]
I'm trying to use glfw3 3.2.1 and when I run the following cmake init it successfully finds the glfw3 package but does not seem to initialize the expected include or library variables.
```
cmake_minimum_required(VERSION 3.7)
PROJECT(test)
find_package(glfw3 REQUIRED)
ADD_EXECUTABLE(test test.cpp)
```
Running make leads to
```
fatal error: 'GLFW/glfw3.h' file not found
```
What am I missing?

**Comment by gentili** [comment]
OSX Sierra 10.12.2
MacPorts 2.3.5
cmake 3.7.1
glfw3 3.2.1

**Comment by zao** [comment]
In short: `target_link_libraries(your_target PRIVATE glfw)`

Exported targets like the ones defined by the GLFW3 CMake files expose the include paths and the libraries to link as properties on the imported `glfw` target. In modern CMake, such things are defined on a per-target basis instead of polluting the scoped global compiler and linker parameters.

As a side note, `test` is a reserved target name by CMake, you should probably name your sample ones something less conflicting.

**Comment by gentili** [comment]
Worked like a charm.  I had tried target_link_libraries(thing glfw3) without success.

Side note: Yes I just inserted 'test' in the example; it's not the actual project name.

Thank you very much for the assistance!
