### ISSUE TITLE
Missing Functionality in the Mir Platform

### ISSUE THREAD

**Issue by BrandonSchaefer** [glfw/glfw#982]
1) Monitor disconnection. Need to handle MirWindowOutputEvents
2) Gamma, need to implement this
3) Setting aspect ratios, need to set the windows min/max aspect (all mir supports)
4) FocusWindow - There is no specific function. The closest is raising a window (which will achieve the wanted behaviour. Focus + Raising the window to the top)
5) Getting the pointers position, by keeping track of an x/y internally and updating per event.

Still a few functions Mir doesnt support.

You can just assign this to me, just want a nicer way to keep track to this. I can also split these up into specific issues. Though the branch for most of this wont be to large!

**Comment by BrandonSchaefer** [comment]
So looking at problem 1) the polling function for monitors. Currently X11:

Creates a deep copy of the current monitors glfw has. Then checks against the currently connected outputs vs the cached monitors from glfw. If any are still around at the end they are disconnected and need to clean up the array. This then adds a worst case N - 1 copies to the left to remove that disconnection in the list.

Thats fine, but I think it'll be much easier/simpler (doesnt mean better!) to each time we poll for monitors, clear the current _glfw.monitors. Then just simply re-add the connected monitors. This incurs a free on the connected outputs/modes/gammas. Then a malloc on the platforms connected outputs/modes/gammas.

This would most likely add some extra memory allocation (eww) but how many times is it expected to even run that code? (Any output change event I would imagine which wouldnt be often, hopefully!) How many monitors are really connected?

Though Im happy to do either way!

Delete all glfw monitors and re-add:
http://paste.ubuntu.com/24302215/

Correctly maintain the list of cached glfw monitors (not actually tested but the main idea):
http://paste.ubuntu.com/24302210/

**Comment by elmindreda** [comment]
The [second implementation](https://paste.ubuntu.com/24302210/) looks really good and I'll gladly merge it.

X11 only makes a shallow copy; only the pointer-to-pointer array is copied. All deep copies of monitor arrays were removed with the introduction of `_glfwInputMonitor` (and was one of the reasons for the change). The worst case you speak of would only occur if all monitors were removed simultaneously, _n_ would still be small and the copies are of pointers only.

If we clear and repopulate the public monitor array at the start of polling then `glfwGetMonitors` will not return correct information (up to and including the calling event) from within the monitor callback. It would also cause duplicate and missing events unless we go back to an array-reconciliation solution similar to the now removed `_glfwInputMonitorChange`.

Allocating new monitor objects for existing monitors would also cause their addresses to change, but the [documentation guarantees](http://www.glfw.org/docs/latest/monitor_guide.html#monitor_object) that monitor objects keep their addresses until disconnection or termination. This is in order to help user code make sense of disconnection events.

**Comment by BrandonSchaefer** [comment]
That makes much more sense, miss read the deep copy bit.  I should read the documentation a bit more then! Thanks, Ill get that correct way up soon!

**Comment by elmindreda** [comment]
> Setting aspect ratios, need to set the windows min/max aspect (all mir supports)

That's fine, just add a __Mir:__ remark to the documentation.

> FocusWindow - There is no specific function. The closest is raising a window (which will achieve the wanted behaviour. Focus + Raising the window to the top)

That's fine too. Again, just add a remark. Every platform has its weird exceptions and I think macOS is still in the lead here.

**Comment by BrandonSchaefer** [comment]
O right, im seeing though now through the documentation! Cool yeah Ill be sure to update the documentation for specific platform quirks. Though need to read through them a bit more as well.

Thanks!

**Comment by startas** [comment]
I dont know if you heard, but canonical is killing unity and mir completely and moving to gnome, so its safe to say that you can remove mir support completely. No need to waste time.

**Comment by tombsar** [comment]
@startas FYI tat question was addressed here: https://github.com/glfw/glfw/issues/984

**Comment by linkmauve** [comment]
Mir support has been removed as of #1336, as Mir developers now recommend using Wayland.
